### ISSUE TITLE
 Error loading script: animatediff.py

### ISSUE THREAD

**Issue by XT-404** [continue-revolution/sd-webui-animatediff#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 12, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

---

### Steps to reproduce the problem

Install new commit  > error

### What should have happened?

.

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
venv "W:\A1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements



Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72


Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 23.7.9, num models: 9
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 12, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

---
Warning: ControlNet failed to load SGM - will use LDM instead.
2023-09-20 18:07:58,894 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: W:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-20 18:07:59,175 - ControlNet - INFO - ControlNet v1.1.410
Warning: ControlNet failed to load SGM - will use LDM instead.
2023-09-20 18:07:59,832 - roop - INFO - roop v0.0.2
2023-09-20 18:07:59,879 - roop - INFO - roop v0.0.2
Loading weights [6f2b175ff8] from W:\A1111\stable-diffusion-webui\models\Stable-diffusion\Anime\Drawing.V1.4.fp16.safetensors
*Deforum ControlNet support: enabled*
Creating model from config: W:\A1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 18.5s (import torch: 2.3s, import gradio: 1.1s, import ldm: 0.6s, other imports: 1.8s, list SD models: 1.6s, load scripts: 6.6s, create ui: 1.9s, gradio launch: 2.5s).
DiffusionWrapper has 859.52 M params.
preload_extensions_git_metadata for 17 extensions took 3.58s
Loading VAE weights specified in settings: W:\A1111\stable-diffusion-webui\models\VAE\vae-Evil-666-Bitch_v100.pt
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 8.0s (load weights from disk: 2.9s, create model: 2.3s, apply weights to model: 1.5s, apply half(): 0.5s, load VAE: 0.2s, move model to device: 0.5s).
```

### Additional information

<img width="760" alt="image" src="https://github.com/continue-revolution/sd-webui-animatediff/assets/128090530/7bf1fc1b-d5d3-4294-beea-3cd002599584">

**Comment by continue-revolution** [comment]
Update your webui to 1.6.0 will solve your problem.

**Comment by XT-404** [comment]
@continue-revolution 
I have already installed on vlad up to date, like A1111 up to date or other version I always have the same error

**Comment by continue-revolution** [comment]
Your console log shows that your webui is v1.4.0. I don’t know anything about vlad because I don’t use it.

You can either update your A1111 webui to v1.6.0 (your terminal will tell you this) or ask vlad to support image_tensor_to_samples. You can also use ‘git checkout’ to revert back to a previous version, where img2gif is not supported.
