### ISSUE TITLE
[Bug]: no generate video or gif 

### ISSUE THREAD

**Issue by armando2804** [continue-revolution/sd-webui-animatediff#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

no save gif / mp4

### Steps to reproduce the problem

1. use  DPM++ 2M Karras,
2. press generate 
3. ...

### What should have happened?

It generates the frames but it does not generate the gif

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
*** Error running postprocess: J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "J:\stable\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 54, in _save
        imageio.mimsave(
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\functions.py", line 302, in mimwrite
        writer = get_writer(uri, format, 'I', **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\functions.py", line 150, in get_writer
        format = formats.search_write_format(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\format.py", line 688, in search_write_format
        if format.can_write(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\format.py", line 196, in can_write
        return self._can_write(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\plugins\pillow.py", line 66, in _can_write
        Image = self._init_pillow()
                ^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\plugins\pillow.py", line 43, in _init_pillow
        raise ImportError('Imageio Pillow requires Pillow, not PIL!')
    ImportError: Imageio Pillow requires Pillow, not PIL!
```

### Console logs

```Shell
*** Error running postprocess: J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "J:\stable\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 54, in _save
        imageio.mimsave(
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\functions.py", line 302, in mimwrite
        writer = get_writer(uri, format, 'I', **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\functions.py", line 150, in get_writer
        format = formats.search_write_format(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\format.py", line 688, in search_write_format
        if format.can_write(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\core\format.py", line 196, in can_write
        return self._can_write(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\plugins\pillow.py", line 66, in _can_write
        Image = self._init_pillow()
                ^^^^^^^^^^^^^^^^^^^
      File "J:\stable\stable-diffusion-webui\venv\Lib\site-packages\imageio\plugins\pillow.py", line 43, in _init_pillow
        raise ImportError('Imageio Pillow requires Pillow, not PIL!')
    ImportError: Imageio Pillow requires Pillow, not PIL!
```

**Comment by zappityzap** [comment]
```ImportError: Imageio Pillow requires Pillow, not PIL!```
This means you have a package issue with ImageIO. Try activating your venv and then install these packages:
```
pip install pillow
pip install imageio[ffmpeg]
```
