### ISSUE TITLE
[Bug]: Cant load the plugin

### ISSUE THREAD

**Issue by thedirptastic** [continue-revolution/sd-webui-animatediff#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Whenever I try to load the plugin I get an error in my terminal and the plugin doesn't load.

### Steps to reproduce the problem

1. Install the plugin
2. Run the webui

### What should have happened?

The plugin should have loaded

### Commit where the problem happens

webui: 68f336bd994bed5442ad95bad6b6ad5564a5409a
extension: 99bcb53d6b9b558f58438f728de8189239b081bd

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--listen --share --enable-insecure-extension-access --xformers
```

### Console logs

```Shell
Since the plugin never loaded, there are no firefox logs, however, here is the stacktrace:

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "/home/derp/AI/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/derp/AI/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/derp/AI/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 8, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "/home/derp/AI/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_latent.py", line 6, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (/home/derp/AI/stable-diffusion-webui/modules/sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "/home/derp/AI/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/derp/AI/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/derp/AI/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_latent.py", line 6, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (/home/derp/AI/stable-diffusion-webui/modules/sd_samplers_common.py)

---
```

### Additional information

I am using python 3.11.5

**Comment by continue-revolution** [comment]
Update your WebUI to 1.6.0 should solve your problem. You are using 1.5.1
