### ISSUE TITLE
[Bug]: motion LoRA loading failed

### ISSUE THREAD

**Issue by xpeng** [continue-revolution/sd-webui-animatediff#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

have a try on Motion LoRA in sd-webui v1.6.0, using mm_sd_v15_v2.ckpt as motion model, then failed in loading. 

### Steps to reproduce the problem

downloaded some motion lora models to `stable-diffusion-webui/models/Lora`, and using mm_sd_v15_v2.ckpt as motion model, then failed in loading.

### What should have happened?

no error

### Commit where the problem happens

webui: 1.6.0
extension: sd-webui-animatediff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
(masterpiece, best quality), 1boy, afro, (((dark skin))), playing guitar, concert, upper body, sweat, stage lights, oversized hawaiian shirt, ((intricate, print, pattern)), happy, necklace, ((bokeh)), jeans, drummer, dynamic pose.
<lora:v2_lora_ZoomOut:1>
Negative prompt: (worst quality, low quality, letterboxed)
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1564496368, Size: 768x768, Model hash: e8d456c42e, Model: toonyou_beta6, Version: v1.6.0
```

### Console logs

```Shell
2023-09-26 14:30:58,889 - AnimateDiff - INFO - AnimateDiff process start.
2023-09-26 14:30:58,890 - AnimateDiff - INFO - You are using mm_sd_v15_v2.ckpt, which has been tested and supported.
2023-09-26 14:30:58,890 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from /mnt/data/aigc/webui/AUTOMATIC1111/stable-diffusion-webui/extensions/sd-webui-animatediff/model/mm_sd_v15_v2.ckpt
2023-09-26 14:31:03,113 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-09-26 14:31:03,428 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2023-09-26 14:31:03,429 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2023-09-26 14:31:03,429 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2023-09-26 14:31:03,429 - AnimateDiff - INFO - Setting DDIM alpha.
2023-09-26 14:31:03,429 - AnimateDiff - INFO - Injection finished.
2023-09-26 14:31:03,430 - AnimateDiff - INFO - Hacking lora to support motion lora
2023-09-26 14:31:03,578 - AnimateDiff - INFO - Loading motion lora v2_lora_ZoomOut from /mnt/data/aigc/webui/AUTOMATIC1111/stable-diffusion-webui/models/Lora/v2_lora_ZoomOut.ckpt
loading network /mnt/data/aigc/webui/AUTOMATIC1111/stable-diffusion-webui/models/Lora/v2_lora_ZoomOut.ckpt: AttributeError
Traceback (most recent call last):
  File "/mnt/data/aigc/webui/AUTOMATIC1111/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 238, in load_networks
    net = load_network(name, network_on_disk)
  File "/mnt/data/aigc/webui/AUTOMATIC1111/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_lora.py", line 44, in mm_load_network
    sd_module = shared.sd_model.network_layer_mapping.get(key, None)
  File "/home/yulei/anaconda3/envs/automatic/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'network_layer_mapping'
```

**Comment by continue-revolution** [comment]
I have no idea why your env did not run https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/Lora/scripts/lora_script.py#L29

If someone knows why please let me know.

**Comment by xpeng** [comment]
error disappeared after update to latest version.

**Comment by lwxbear** [comment]
hi，i have the same error, please tell me , what is the latest version you update? animatediff or lora?

**Comment by sourit2001** [comment]
I have the same issue,did not fixed yet. SD is 1.8 version
