### ISSUE TITLE
[Bug]: RuntimeError: CUDA error: invalid configuration argument     CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by baomuhedao** [continue-revolution/sd-webui-animatediff#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

*** Arguments: ('task(set5n5h4aijafhj)', 'a cute girl  is dacing', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x7fa25c4b0520>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.animatediff_ui.AnimateDiffProcess object at 0x7fa0d5a07f70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa25a4704f0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa101f15d90>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fa0f6304a90>, None, False, '0', '/home/ec2-user/stable-diffusion-webui/models/roop/inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, '🔄', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/home/ec2-user/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_mm.py", line 86, in mm_tes_forward
        x = layer(x, context)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 84, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 148, in forward
        hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, video_length=video_length)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 210, in forward
        hidden_states = attention_block(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 565, in forward
        hidden_states = self._memory_efficient_attention(query, key, value, attention_mask, optimizer_name)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 465, in _memory_efficient_attention
        hidden_states = xformers.ops.memory_efficient_attention(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
        out, *_ = op.apply(inp, needs_gradient=False)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/xformers/ops/fmha/cutlass.py", line 175, in apply
        out, lse, rng_seed, rng_offset = cls.OPERATOR(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/_ops.py", line 502, in __call__
        return self._op(*args, **kwargs or {})
    RuntimeError: CUDA error: invalid configuration argument
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Steps to reproduce the problem

1. Go to txt2img
2. Write a prompt: "a girl is dacing"
3. SD module is realisticVisionV51_v51VAE.safetensors [15012c538f]
4. SD VAE is Automatic
5. Sampling method: DPM++ 2M Karras
6. Enable  AnimatedDiff ,  all params  are default value
7. Click  generate

### What should have happened?

a gif  is generated  normally

### Commit where the problem happens

webui:  1.6.0
extension:   AnimatedDiff: 1.6.0

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
none
```

### Additional information

AnimatedDiff  1.6.0 是基于sd-webui的哪个版本生成开发的？

**Comment by continue-revolution** [comment]
#101
