### ISSUE TITLE
[Bug]: CANNOT INSTALL auto1111 web ui extension

### ISSUE THREAD

**Issue by LIQUIDMIND111** [continue-revolution/sd-webui-animatediff#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

i get this error.

   check_access()
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\ui_extensions.py", line 21, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags

and will not install extension

### Steps to reproduce the problem

1. Go to .... auto1111 extensions
2. Press .... install from https://github.com/continue-revolution/sd-webui-animatediff.git 
3. ... will get error message

### What should have happened?

install the animatediff extension

### Commit where the problem happens

webui: python: 3.10.9  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0  •  commit: [22bcc7be]
extension: https://github.com/continue-revolution/sd-webui-animatediff.git

### Command Line Arguments

```Shell
Launching Web UI with arguments: --xformers --api --cors-allow-origins=https://www.painthua.com --listen
```

### Console logs

```Shell
Error completing request
Arguments: ('', 'https://github.com/continue-revolution/sd-webui-animatediff.git') {}
Traceback (most recent call last):
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\ui_extensions.py", line 133, in install_extension_from_url
    check_access()
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\ui_extensions.py", line 21, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```

**Comment by passionlu** [comment]
--enable-insecure-extension-access

**Comment by LIQUIDMIND111** [comment]
> --enable-insecure-extension-access

ok that worked to install but now after restarting auto111 i get htis error:

Error loading script: animatediff.py
Traceback (most recent call last):
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 9, in <module>
    from scripts.animatediff_infv2v import AnimateDiffInfV2V
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 2, in <module>
    from modules.sd_samplers_cfg_denoiser import CFGDenoiser
ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'

Error loading script: animatediff_infv2v.py
Traceback (most recent call last):
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 2, in <module>
    from modules.sd_samplers_cfg_denoiser import CFGDenoiser
ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'

Error loading script: animatediff_latent.py
Traceback (most recent call last):
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 6, in <module>
    from modules.sd_samplers_common import (approximation_indexes,
ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (C:\TEMP\Stablediff\Autom111\stable-diffusion-webui\modules\sd_samplers_common.py)

**Comment by continue-revolution** [comment]
update your webui to 1.6.0

**Comment by LIQUIDMIND111** [comment]
> update your webui to 1.6.0

ok i thought that would be the issue, thanks

**Comment by LIQUIDMIND111** [comment]
> update your webui to 1.6.0

hello, i installed a NEW repo of auto1111 with version 1.6 and i installed the animatediff extension with no problem, but now it it stuck here ----- 
![Screenshot 2023-09-30 012656](https://github.com/continue-revolution/sd-webui-animatediff/assets/112510084/085c6aac-0511-404d-bda0-90edeba67a9e) 

even with default settings...... 
![Screenshot 2023-09-30 012631](https://github.com/continue-revolution/sd-webui-animatediff/assets/112510084/31b72cec-6898-463a-adb8-d42d4eed4365) 

any ideas???

**Comment by LIQUIDMIND111** [comment]
> update your webui to 1.6.0

my gpu and vram is 6gb but im using XFORMERS.... is 6gb bad even with xformers?
