### ISSUE TITLE
[Bug]: Video input & FILM output error

### ISSUE THREAD

**Issue by zopi4k** [continue-revolution/sd-webui-animatediff#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

• 1 ] **Input Video**

When I put a Video.mp4 in Video source it say during the generate ...

On web-ui navigator :
```
error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'imwrite' > Overload resolution failed: > - Can't convert object to 'str' for 'filename' > - Can't convert object to 'str' for 'filename'
```

On terminal :
```

*** Error completing request
*** Arguments: ('task(jzjnz5q31sgbp2f)', 'redhead pixie haircut , iridescent crop top', '', ['(low quality:1.3)'], 20, 'Euler a', 1, 1, 7, 512, 300, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC8344EB60>, 0, False, '', 0.8, 3741782654, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001FDCB26C880>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FC86167AC0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FC86164D30>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FC861653F0>, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'CodeFormer', 1, 1, 'None', 1, 1, ['After Upscaling/Before Restore Face'], 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, False, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, '0', '0', False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, [], 30, '', 4, [], 1, '', '', '', '') {}
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 66, in hacked_processing_process_images_hijack
        global_input_frames = get_input_frames()
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 45, in get_input_frames
        cv2.imwrite(tmp_frame_dir/f"{frame_count}.png", frame)
    cv2.error: OpenCV(4.8.0) : -1: error: (-5:Bad argument) in function 'imwrite'
    > Overload resolution failed:
    >  - Can't convert object to 'str' for 'filename'
    >  - Can't convert object to 'str' for 'filename'
```

• 2 ] **Save in FILM**

When I activate the Mp4 or GIF output file + FILM enable ...

On web-ui navigator :
- no Video and no Gif exported .. only the frames PNG

On terminal :
```
FILM progress:  88%|███████████████████████████████████████████████████████████        | 15/17 [00:12<00:01,  1.25it/s]
*** Error running postprocess: D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 73, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 34, in output
        video_list = self._interp(p, params, video_list, filename)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 97, in _interp
        run_film_interp_infer(
      File "D:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\src\film_interpolation\film_inference.py", line 90, in run_film_interp_infer
        prediction = model(x0, x1, dt)
      File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
    RuntimeError: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/interpolator.py", line 15, in forward
        x1: Tensor,
        batch_dt: Tensor) -> Tensor:
        _0 = (self).debug_forward(x0, x1, batch_dt, )
              ~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (_0["image"])[0]
      def debug_forward(self: __torch__.interpolator.Interpolator,
      File "code/__torch__/interpolator.py", line 29, in debug_forward
        feature_pyramids = [_2, _3]
        predict_flow = self.predict_flow
        forward_residual_flow_pyramid = (predict_flow).forward(feature_pyramids[0], feature_pyramids[1], )
                                         ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        predict_flow0 = self.predict_flow
        backward_residual_flow_pyramid = (predict_flow0).forward(feature_pyramids[1], feature_pyramids[0], )
      File "code/__torch__/pyramid_flow_estimator.py", line 14, in forward
        levels = torch.len(feature_pyramid_a)
        _predictor = self._predictor
        v = (_predictor).forward(feature_pyramid_a[-1], feature_pyramid_b[-1], )
             ~~~~~~~~~~~~~~~~~~~ <--- HERE
        residuals = [v]
        _1 = torch.sub(levels, 2)
      File "code/__torch__/pyramid_flow_estimator.py", line 69, in forward
        features_a: Tensor,
        features_b: Tensor) -> Tensor:
        net = torch.cat([features_a, features_b], 1)
              ~~~~~~~~~ <--- HERE
        _convs = self._convs
        _0 = getattr(_convs, "0")

    Traceback of TorchScript, original code (most recent call last):
      File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 160, in forward
        @torch.jit.export
        def forward(self, x0, x1, batch_dt) -> torch.Tensor:
            return self.debug_forward(x0, x1, batch_dt)['image'][0]
                   ~~~~~~~~~~~~~~~~~~ <--- HERE
      File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 109, in debug_forward

            # Predict forward flow.
            forward_residual_flow_pyramid = self.predict_flow(feature_pyramids[0], feature_pyramids[1])
                                            ~~~~~~~~~~~~~~~~~ <--- HERE

            # Predict backward flow.
      File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\pyramid_flow_estimator.py", line 123, in forward
            """
            levels = len(feature_pyramid_a)
            v = self._predictor(feature_pyramid_a[-1], feature_pyramid_b[-1])
                ~~~~~~~~~~~~~~~ <--- HERE
            residuals = [v]
            for i in range(levels - 2, len(self._predictors) - 1, -1):
      File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\pyramid_flow_estimator.py", line 72, in forward
              A tensor with optical flow from A to B
            """
            net = torch.cat([features_a, features_b], dim=1)
                  ~~~~~~~~~ <--- HERE
            for conv in self._convs:
                net = conv(net)
    RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 5 but got size 8 for tensor number 1 in the list.
```

### Steps to reproduce the problem

•1] Import Movie

1. Go to Txt2Img
2. Press Enable AnimateDiff
3. Import the video in the Video source ( .MP4 512x512px exported by Flowframe h265 ) I can see and play the video in the web-ui
4. Open tab of Control Net
5. Enable and Chose the Control Type open pose or depth
6. Run Generate ... have the error message.

But if I test "Video path" folder in AnimateDiff it's work fine with control net.

•2] Export FILM

1. Go to Txt2Img
2. Press Enable AnimateDiff
3. Enable "FILM" + "MP4"
6. Run Generate ... have the error message only in terminal.

Yesterday works ... today with update .... no.

### What should have happened?

•1] Import Movie

When I generate, the move turn a frame cut (16 frames if 16 frames have called) to create some input in control net like the "Video path" section.

•2] Export FILM

Export Gif and MP4 (if enable) when I chose to export FILM.

### Commit where the problem happens

webui: 1.6.0
extension:  AnimateDiff v1.7.0
ControlNet v1.1.410 
Deforum v3.0 (I think... hard to find the version ... last commit in 26/09/2023)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--no-half-vae --api --medvram-sdxl --medvram
```

### Console logs

```Shell
No error in the console of navigator.
```

### Additional information

A (HUGE thank you:1.5) for everything you do, I hope that, like us, you will have the pleasure of testing what you have created!

**Comment by continue-revolution** [comment]
@zappityzap

**Comment by zappityzap** [comment]
Thank you for the detailed report. I had some similar errors last night about TorchScript when running FILM interpolation. I'm not sure what solved it but I updated A1111, Deforum and ControlNet extensions, then restarted the webui and cleared browser cache.

I'll test with video input and ControlNet soon.

**Comment by pellaaa93** [comment]
same here, tried with different input resolutions but always get that error.
