### ISSUE TITLE
[Bug]: FILM output not merging due to file "being used by another process"

### ISSUE THREAD

**Issue by ManOrMonster** [continue-revolution/sd-webui-animatediff#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

FILM output merging was working last night. After updating today, it no longer works. Always says:

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'outputs/txt2img-images/AnimateDiff/tmp/00538-773393486\\frame_000000000.png'`

With different path/filename each time, of course.

Makes no difference if using ControlNet or not. Restarting webUI didn't resolve.

### Steps to reproduce the problem

1. Enable AnimateDiff in txt2img
2. Select "FILM"
3. Generate

### What should have happened?

The resultant frames should be merged into an animation.

### Commit where the problem happens

webui: 5ef669d
extension: 6e02f01

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Total frames to FILM-interpolate: 31. Total frame-pairs: 30.
FILM progress: 100%|███████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.44it/s]
Interpolation done in 7.28 seconds!
*** Error running postprocess: C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 816, in move
        os.rename(src, real_dst)
    PermissionError: [WinError 5] Access is denied: 'outputs/txt2img-images/AnimateDiff/tmp/00538-773393486' -> 'outputs/txt2img-images/AnimateDiff/interp\\00538-773393486'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\stable-diffusion\automatic1111\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff.py", line 73, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 34, in output
        video_list = self._interp(p, params, video_list, filename)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 111, in _interp
        shutil.move(save_folder, save_interp_path)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 834, in move
        rmtree(src)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 750, in rmtree
        return _rmtree_unsafe(path, onerror)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 620, in _rmtree_unsafe
        onerror(os.unlink, fullname, sys.exc_info())
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 618, in _rmtree_unsafe
        os.unlink(fullname)
    PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'outputs/txt2img-images/AnimateDiff/tmp/00538-773393486\\frame_000000000.png'
```

### Additional information

Tried this in Edge browser too, same issue. I can't think of anything outside of auto1111 that would make those files be in use suddenly.

**Comment by continue-revolution** [comment]
@zappityzap

**Comment by zappityzap** [comment]
I don't have a Windows machine to test with. I can think of a lot of things in Windows that could be locking files (AV, thumbnails, etc.) but file handling might improve with this:
```diff
diff --git a/scripts/animatediff_output.py b/scripts/animatediff_output.py
index 7ff0464..4b17d7f 100644
--- a/scripts/animatediff_output.py
+++ b/scripts/animatediff_output.py
@@ -102,7 +102,11 @@ class AnimateDiffOutput:
 
         # load deforum output frames and replace video_list
         interp_frame_paths = sorted(glob.glob(os.path.join(save_folder, '*.png')))
-        video_list = [Image.open(f) for f in interp_frame_paths]
+        video_list = []
+        for f in interp_frame_paths:
+            with Image.open(f) as img:
+                img.load()
+                video_list.append(img)
         
         # if saving PNG, also save interpolated frames
         if "PNG" in params.format:
```
It's possible that Image.open(f) is keeping the file open, but the Pillow docs say using .load() will close the file (unless it has multiple frames).

It does no harm for Linux so I'll open a PR.

**Comment by ManOrMonster** [comment]
@zappityzap Yep, it's fixed. Thanks!
