### ISSUE TITLE
[Bug]: TypeError: Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'

### ISSUE THREAD

**Issue by vulcandragon** [continue-revolution/sd-webui-animatediff#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Trying to install the extension gives the following error:
TypeError: Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'

Removing the half installed folder and trying again give the same issue.

version: v1.6.0  •  python: 3.10.0  •  torch: 2.0.1+cu118 

### Steps to reproduce the problem

Extensions
Install from URL
paste https://github.com/continue-revolution/sd-webui-animatediff
Click install button

### What should have happened?

Extension should have installed

### Commit where the problem happens

webui: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
.\webui1.bat --api --opt-split-attention --opt-sdp-no-mem-attention --no-half-vae
```

### Console logs

```Shell
*** Error completing request
*** Arguments: ('', 'https://github.com/continue-revolution/sd-webui-animatediff', '') {}
    Traceback (most recent call last):
      File "C:\Users\cwhite\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\cwhite\stable-diffusion-webui\modules\ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "C:\Users\cwhite\stable-diffusion-webui\modules\ui_extensions.py", line 369, in install_extension_from_url
        for submodule in repo.submodules:
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 422, in submodules
        return Submodule.list_items(self)
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\util.py", line 1189, in list_items
        out_list.extend(cls.iter_items(repo, *args, **kwargs))
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\objects\submodule\base.py", line 1373, in iter_items
        pc = repo.commit(parent_commit)  # parent commit instance
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 614, in commit
        return self.rev_parse(str(rev) + "^0")
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\repo\fun.py", line 250, in rev_parse
        obj = cast(Commit_ish, name_to_object(repo, rev[:start]))
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\repo\fun.py", line 187, in name_to_object
        return Object.new_from_sha(repo, hex_to_bin(hexsha))
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\objects\base.py", line 95, in new_from_sha
        inst = get_object_type_by_name(oinfo.type)(repo, oinfo.binsha)
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\objects\commit.py", line 146, in __init__
        super(Commit, self).__init__(repo, binsha)
      File "C:\Users\cwhite\stable-diffusion-webui\venv\lib\site-packages\git\objects\base.py", line 63, in __init__
        super(Object, self).__init__()
      File "C:\Program Files\Python310\lib\typing.py", line 1422, in _no_init_or_replace_init
        cls.__init__(self, *args, **kwargs)
    TypeError: Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
```

**Comment by vulcandragon** [comment]
This appears to be an issue with a py file in the main git.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8047

"I worked around it by modifying ui_extensions.py, changing

        with git.Repo.clone_from(url, tmpdir) as repo:
            repo.remote().fetch()
            for submodule in repo.submodules:
                submodule.update()
to just

        git.Repo.clone_from(url, tmpdir)"
