### ISSUE TITLE
[Bug]:  AttributeError: 'str' object has no attribute 'info'

### ISSUE THREAD

**Issue by F0xbite** [continue-revolution/sd-webui-animatediff#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Using webui, everything is working fine. I'm 99.9% there in getting the API to work, but it gives me this error after creating the gif:
```
      File "C:\a1111install\stable-diffusion-webui\modules\api\api.py", line 110, in encode_pil_to_base64
        for key, value in image.info.items():
    AttributeError: 'str' object has no attribute 'info'
```    
The process seems to complete, as the expected GIF file is in the output folder, but it seems to be looking for "info" in the response but (i guess) it isn't there, resulting in a 500 response.

I'm using the latest commits for your extension, A1111, controlnet, and deforum.

 I am triggering AnimateDiff with this JSON (as an example) to the A1111 txt2img endpoint:
```
{
    "prompt": "dog",
    "negative_prompt": "ugly",
    "seed": -1,
    "width": 512,
    "height": 512,
    "steps": 15,
    "sampler_name": "Euler",
    "cfg_scale": 7,
    "resize_mode": 0,
    "restore_faces": false,
    "enable_hr": false,
    "hr_upscaler": "Latent",
    "hr_scale": 2,
    "denoising_strength": 0.65,
    "conditioning_strength": 0,
    "alwayson_scripts": {
        "AnimateDiff": {
            "args": [
                {
                    "enable": true,
                    "video_length": 16,
                    "format": ["GIF"],
                    "loop_number": 0,
                    "fps": 8,
                    "model": "mm_sd_v15_v2.ckpt",
                    "reverse": [],
                    "latent_power": 1,
                    "latent_scale": 32,
                    "last_frame": null,
                    "latent_power_last": 1,
                    "latent_scale_last": 32
                }
            ]
        }
    }
}
```

BTW - It seems your example API json payload is incorrect on the main page. It shows you passing "GIF" as a string, but I was getting an error that it didn't recognize the value until i changed it to a list ["GIF"].  Since no one else is even talking about the API, I am getting a feeling very few (or none) have actually tried using the API before.

I could work around this issue by expecting the error 500 response and grabbing the file, but that seemed messy and not the way it was intended to work. Any guidance you can offer is appreciated. Thanks!

### Steps to reproduce the problem

1. POST to txt2img endpoint for A1111 SD (using example payload above)
2. witness error

### What should have happened?

A successful 200 response, with (hopefully) a JSON response including 'info' (maybe including the path/file for the gif? I don't know because there's no documentation and I haven't gotten a successful response from the API yet)

### Commit where the problem happens

webui: A1111 1.6.0 (latest)
extension: (All latest commits) AnimateDiff extension, ControlNet, Deforum

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --listen --enable-insecure-extension-access --api --api-log --no-half-vae --deforum-api
```

### Console logs

```Shell
*** API error: POST: http://localhost:7860/sdapi/v1/txt2img {'error': 'AttributeError', 'detail': '', 'body': '', 'errors': "'str' object has no attribute 'info'"}
    Traceback (most recent call last):
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\a1111install\stable-diffusion-webui\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "C:\a1111install\stable-diffusion-webui\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "C:\a1111install\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "C:\a1111install\stable-diffusion-webui\modules\api\api.py", line 386, in text2imgapi
        b64images = list(map(encode_pil_to_base64, processed.images)) if send_images else []
      File "C:\a1111install\stable-diffusion-webui\modules\api\api.py", line 110, in encode_pil_to_base64
        for key, value in image.info.items():
    AttributeError: 'str' object has no attribute 'info'
```

**Comment by continue-revolution** [comment]
This is because webui does this after generation
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/api/api.py#L385
then this
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/api/api.py#L110
It seems to me that A1111 does not support returning gif at this time. Previously the behaviour is that API will return a list of frames; then someone did a PR which changed the behavior into returning base64 encoded video. I'm not sure what you want. The simplist way is to revert back to returning a list of frames.

**Comment by F0xbite** [comment]
I see. Well, with Deforum's API (separate API - not integrated with A1111's API) has its own endpoint for batches that you have to poll until it returns a successful response for the job, and that response json includes the outdir path and file for the GIF/MP4, which I then grab. I would be ok with something like that, but I know this doesn't work in quite the same fashion.

Regardless, I appreciate the quick response!

**Comment by continue-revolution** [comment]
Now that I have reverted back to responding a list of frames.

**Comment by victorbianconi** [comment]
> Now that I have reverted back to responding a list of frames.

How did you do that exactly?

**Comment by continue-revolution** [comment]
I changed one line of code, that’s all

**Comment by ejuoy** [comment]
> I changed one line of code, that’s all

where changed
