### ISSUE TITLE
[Bug]: API throwing errors, producing single image gif

### ISSUE THREAD

**Issue by KimMatt** [continue-revolution/sd-webui-animatediff#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I'm trying to use AnimateDiff's api and passing these arguments in. (prompt and seed are overwritten in the function I'm calling and don't stay as None)

```
"prompt": None,
"negative_prompt": "logo, watermark, shutterstock, text, badhandv4,easynegative,ng_deepnegative_v1_75t:0.2",
"seed": None,
"sampler_name": "DPM++ 3M SDE Karras",
"steps": 40,
"cfg_scale": 6.5,
"width": 512,
"height": 512,
"restore_faces": False,
"sampler_index": "DPM++ 3M SDE Karras",
"send_images": False,
"save_images": True,
"alwayson_scripts": {
		"AnimateDiff": {
			"args": [{
				"enable": True,
				"video_length": 24,
				"format": "GIF",
				"loop_number": 0,
				"fps": 8,
				"model": "mm_sd_v15_v2.ckpt",
				"closed_loop": True
			}]
		}
	}
```

However, I'm seeing these errors thrown.
```
*** Error running before_process: D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\Code\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 46, in before_process
        params.set_p(p)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 84, in set_p
        self._check()
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 78, in _check
        assert not set(["GIF", "MP4", "PNG"]).isdisjoint(
    AssertionError: At least one saving format should be selected.

---
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.03it/s]
*** Error running postprocess: D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/s]
    Traceback (most recent call last):
      File "D:\Code\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'
```

### Steps to reproduce the problem

1. Using the API, pass in this payload to generate an animatediff gif
2. Observe result

### What should have happened?

GIF generated

### Commit where the problem happens

webui: 

```commit 5ef669de080814067961f28357256e8fe27544f4 (HEAD -> master, tag: v1.6.0, origin/release_candidate, origin/master, origin/HEAD)
Merge: c9c8485b e7965a5e
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Thu Aug 31 07:38:34 2023 +0300

    Merge branch 'release_candidate'
```
   
extension: 
```commit a3b0bee4d77983cf132f60ba452c0c4088e50997 (HEAD -> main, origin/main, origin/HEAD)
Author: Ray <31238196+AnyiRao@users.noreply.github.com>
Date:   Mon Sep 25 19:51:52 2023 -0700

    Update shot camera movement term
```

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set CUDA_LAUNCH_BLOCKING=1
set TORCH_USE_CUDA_DSA=1
set COMMANDLINE_ARGS= --no-half --xformers --api
```

### Console logs

```Shell
on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 165.7s (prepare environment: 155.3s, import torch: 3.8s, import gradio: 0.9s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 2.1s, create ui: 1.2s, gradio launch: 0.4s, add APIs: 0.1s).
Applying attention optimization: xformers... done.
Model loaded in 5.7s (load weights from disk: 0.7s, create model: 0.6s, apply weights to model: 2.0s, apply float(): 1.4s, calculate empty prompt: 0.9s).
D:\Code\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:130: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  visual_regions = gr.Gallery(label="Regions").style(grid=(4, 4, 4, 8), height="auto")
D:\Code\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:130: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  visual_regions = gr.Gallery(label="Regions").style(grid=(4, 4, 4, 8), height="auto")
2023-10-02 14:29:04,246 - AnimateDiff - INFO - AnimateDiff process start.
*** Error running before_process: D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\Code\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 46, in before_process
        params.set_p(p)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 84, in set_p
        self._check()
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 78, in _check
        assert not set(["GIF", "MP4", "PNG"]).isdisjoint(
    AssertionError: At least one saving format should be selected.

---
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.03it/s]
*** Error running postprocess: D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/s]
    Traceback (most recent call last):
      File "D:\Code\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\Code\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'

---
```

### Additional information

Everything works great via web ui interface. This only happens when using API.

**Comment by KimMatt** [comment]
Also it's not an xformers issue. I'm using sdp.
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/5519589/85107056-daa8-4e88-b695-b1b2c5005697)

**Comment by continue-revolution** [comment]
The format should be a list of str. This is a problem on my end (readme).

**Comment by KimMatt** [comment]
Got it, that seemed to do the trick. Also, where do I find parameter names for variables like context batch size and closed loop that are not in readme example?

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_ui.py#L22

You should be able to easily understand this file. Readme will be updated later.

**Comment by KimMatt** [comment]
Thank you!

**Comment by kilimchoi** [comment]
this happens because module is not properly loaded. Check out https://docs.randomseed.co/api-reference/v1/animatediffusion 
We've already implemented this.
