### ISSUE TITLE
[Bug]:  RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Half for the source.

### ISSUE THREAD

**Issue by zethfoxster** [continue-revolution/sd-webui-animatediff#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

    Traceback (most recent call last):
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\WebUi\auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 104, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\WebUi\auto1111\stable-diffusion-webui\extensions\sd-webui-comfyui\lib_comfyui\webui\patches.py", line 104, in p_sample_patch
        x = original_function(*args, **kwargs)
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\sd_samplers_timesteps.py", line 158, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\sd_samplers_timesteps.py", line 158, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\WebUi\auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\WebUi\auto1111\stable-diffusion-webui\modules\sd_samplers_timesteps_impl.py", line 24, in ddim
        e_t = model(x, timesteps[index].item() * s_in, **extra_args)
      File "C:\WebUi\auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\WebUi\auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 247, in mm_cfg_forward
        x_out = mm_sd_forward(self, x_in, sigma_in, cond_in, image_cond_in, make_condition_dict)
      File "C:\WebUi\auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 164, in mm_sd_forward
        x_out[_context] = self.inner_model(x_in[_context], sigma_in[_context], cond=make_condition_dict(cond_in[_context], image_cond_in[_context]))
    RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Half for the source.

### Steps to reproduce the problem

worked 2 days ago, updated, now i get this...

### What should have happened?

it should have been able to make a gif

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
n/a
```

**Comment by zethfoxster** [comment]
the above is on auto1111 when you try to use it.
below im including the error sdnext gives now, which wont even load the extension

```18:13:33-870718 ERROR    Module load: extensions\sd-webui-animatediff\scripts\animatediff.py: ModuleNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\WebUi\StableDiffusion_July_redo\automatic\modules\script_loading.py:18 in load_module                             │
│                                                                                                                      │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                               │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                                                              │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging                                               │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ C:\WebUi\StableDiffusion_July_redo\automatic\extensions\sd-webui-animatediff\scripts\animatediff.py:9 in <module>    │
│                                                                                                                      │
│     8 from scripts.animatediff_cn import AnimateDiffControl                                                          │
│ ❱   9 from scripts.animatediff_infv2v import AnimateDiffInfV2V                                                       │
│    10 from scripts.animatediff_latent import AnimateDiffI2VLatent                                                    │
│                                                                                                                      │
│ C:\WebUi\StableDiffusion_July_redo\automatic\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py:11 in     │
│ <module>                                                                                                             │
│                                                                                                                      │
│    10 from modules.script_callbacks import AfterCFGCallbackParams, cfg_after_cfg_callback                            │
│ ❱  11 from modules.sd_samplers_cfg_denoiser import CFGDenoiser, catenate_conds, subscript_cond                       │
│    12                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'
18:13:33-895718 ERROR    Module load: extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py: ModuleNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\WebUi\StableDiffusion_July_redo\automatic\modules\script_loading.py:18 in load_module                             │
│                                                                                                                      │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                               │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                                                              │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging                                               │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ C:\WebUi\StableDiffusion_July_redo\automatic\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py:11 in     │
│ <module>                                                                                                             │
│                                                                                                                      │
│    10 from modules.script_callbacks import AfterCFGCallbackParams, cfg_after_cfg_callback                            │
│ ❱  11 from modules.sd_samplers_cfg_denoiser import CFGDenoiser, catenate_conds, subscript_cond                       │
│    12                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'
```

**Comment by alenknight** [comment]
i have the same issue.  also Animatediff upon install tried to do some CUDA stuff and returned tons of errors about access denied.  my other A4 installs don't have these issues.

**Comment by RoversCode** [comment]
i have the same issue.

**Comment by RoversCode** [comment]
i have the same issue when i use DDIM.  gpu is 4090.

**Comment by continue-revolution** [comment]
@RoversCode Thanks for providing information about DDIM. I will fix it in a minute.

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/commit/f20f57f654c7348fe0847cebef2e7d8912983cd5
resolved
