### ISSUE TITLE
[Bug]: RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by elfgoose** [continue-revolution/sd-webui-animatediff#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Was working, then suddenly throwing up error every time

### Steps to reproduce the problem

Happens every time

### What should have happened?

Should have produced a gif

### Commit where the problem happens

webui: 1.6.0
extension: [b192a255](https://github.com/continue-revolution/sd-webui-animatediff/commit/b192a2551a5ed66d4a3ce58d5d19a8872abc87ca)

### Command Line Arguments

```Shell
--listen --api --medvram --reinstall-xformers --xformers --theme dark --opt-sdp-no-mem-attention --enable-insecure-extension-access --no-half --no-half-vae
```

### Console logs

```Shell
Already up to date.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing xformers
Checking ReActor requirements... Ok
Launching Web UI with arguments: --listen --api --medvram --reinstall-xformers --xformers --theme dark --opt-sdp-no-mem-attention --enable-insecure-extension-access --no-half --no-half-vae
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.9.3, num models: 12
2023-10-03 12:08:43,730 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-03 12:08:44,387 - ControlNet - INFO - ControlNet v1.1.410
sd-webui-prompt-all-in-one background API service started successfully.
12:08:47 - ReActor - STATUS - Running v0.4.2-b3
Loading weights [15012c538f] from C:\AI\Image AI\SDNEW\webui\models\Stable-diffusion\sd_1.5\realisticVisionV51_v51VAE.safetensors
Creating model from config: C:\AI\Image AI\SDNEW\webui\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 60.2s (prepare environment: 7.5s, import torch: 4.6s, import gradio: 15.6s, setup paths: 7.1s, initialize shared: 0.8s, other imports: 5.2s, setup codeformer: 1.1s, setup gfpgan: 0.3s, list SD models: 0.2s, load scripts: 9.2s, initialize extra networks: 0.1s, create ui: 0.9s, gradio launch: 5.6s, add APIs: 0.1s, app_started_callback: 2.0s).
Applying attention optimization: xformers... done.
Model loaded in 11.8s (load weights from disk: 0.5s, create model: 1.0s, apply weights to model: 4.7s, apply float(): 2.6s, load textual inversion embeddings: 0.2s, calculate empty prompt: 2.7s).
2023-10-03 12:09:11,915 - AnimateDiff - STATUS - AnimateDiff process start.
2023-10-03 12:09:11,915 - AnimateDiff - STATUS - You are using mm_sd_v15_v2.ckpt, which has been tested and supported.
2023-10-03 12:09:11,915 - AnimateDiff - STATUS - Loading motion module animatediffMotion_v15V2.ckpt from C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\model\animatediffMotion_v15V2.ckpt
2023-10-03 12:09:15,965 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-10-03 12:09:16,714 - AnimateDiff - STATUS - Injecting motion module animatediffMotion_v15V2.ckpt into SD1.5 UNet middle block.
2023-10-03 12:09:16,715 - AnimateDiff - STATUS - Injecting motion module animatediffMotion_v15V2.ckpt into SD1.5 UNet input blocks.
2023-10-03 12:09:16,716 - AnimateDiff - STATUS - Injecting motion module animatediffMotion_v15V2.ckpt into SD1.5 UNet output blocks.
2023-10-03 12:09:16,716 - AnimateDiff - STATUS - Setting DDIM alpha.
2023-10-03 12:09:16,720 - AnimateDiff - STATUS - Injection finished.
2023-10-03 12:09:16,721 - AnimateDiff - STATUS - Hacking lora to support motion lora
2023-10-03 12:09:16,721 - AnimateDiff - STATUS - Hacking CFGDenoiser forward function.
2023-10-03 12:09:16,721 - AnimateDiff - STATUS - Hacking ControlNet.
  0%|                                                                                           | 0/30 [00:01<?, ?it/s]
*** Error completing request
*** Arguments: ('task(vhqnzqk0cqmctqa)', 'A beautiful woman running through a field of poppies,', '', [], 30, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001614E595810>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, 'GFPGAN', False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001614E594550>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001614E4DBB80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001614E578880>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001614E4DBF10>, <PIL.Image.Image image mode=RGB size=1132x1415 at 0x1614E595EA0>, True, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, '8x_NMKD-Faces_160000_G', 3.7, 0.8, False, True, 1, 0, 0, False, 0.5, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\AI\Image AI\SDNEW\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\AI\Image AI\SDNEW\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\AI\Image AI\SDNEW\webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 104, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\AI\Image AI\SDNEW\webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 247, in mm_cfg_forward
        x_out = mm_sd_forward(self, x_in, sigma_in, cond_in, image_cond_in, make_condition_dict)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 164, in mm_sd_forward
        x_out[_context] = self.inner_model(x_in[_context], sigma_in[_context], cond=make_condition_dict(cond_in[_context], image_cond_in[_context]))
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 86, in mm_tes_forward
        x = layer(x, context)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\motion_module.py", line 86, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\motion_module.py", line 150, in forward
        hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, video_length=video_length)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\motion_module.py", line 212, in forward
        hidden_states = attention_block(
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\motion_module.py", line 567, in forward
        hidden_states = self._memory_efficient_attention(query, key, value, attention_mask, optimizer_name)
      File "C:\AI\Image AI\SDNEW\webui\extensions\sd-webui-animatediff\motion_module.py", line 467, in _memory_efficient_attention
        hidden_states = xformers.ops.memory_efficient_attention(
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 310, in _memory_efficient_attention_forward
        out, *_ = op.apply(inp, needs_gradient=False)
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
        out, lse, rng_seed, rng_offset = cls.OPERATOR(
      File "C:\AI\Image AI\SDNEW\system\python\lib\site-packages\torch\_ops.py", line 502, in __call__
        return self._op(*args, **kwargs or {})
    RuntimeError: CUDA error: invalid configuration argument
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


---
```

**Comment by illuculent** [comment]
Same issue here.

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff#update v1.5.2

The option is in `Settings/AnimateDiff`

**Comment by ArlanCooper** [comment]
> https://github.com/continue-revolution/sd-webui-animatediff#update v1.5.2
> 
> The option is in `Settings/AnimateDiff`

what does this mean？ should I return the version to v1.5.2?

**Comment by continue-revolution** [comment]
You should read v1.5.2 update information there to understand what you should do.
