### ISSUE TITLE
[Bug]: the program does not start. or is not visible

### ISSUE THREAD

**Issue by armando2804** [continue-revolution/sd-webui-animatediff#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Already up to date.
venv "J:\stable\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --theme dark
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "J:\stable\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 14, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "J:\stable\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

 python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
@echo off

set PYTHON="C:\Users\Ing. Armando Rivera\AppData\Local\Programs\Python\Python310\python.exe"
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --theme dark
Git pull
call webui.bat
```

### Console logs

```Shell
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "J:\stable\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
```

### Additional information

 python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

**Comment by continue-revolution** [comment]
#118
