### ISSUE TITLE
[Bug]: AnimateDIFF do nothing

### ISSUE THREAD

**Issue by ShmuelRonen** [continue-revolution/sd-webui-animatediff#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I work with the standalone version of AnimateDIFF and it's worked fine on my RTX 3090. Today I installed your adaptation to automatic1111.
I put the motion models and checked the Enable AnimateDiff option, but it only makes the regular text2img process as a PNG file.
I'm not sure what's going wrong.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

make a gif file

### Commit where the problem happens

webui: Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements
extension: 

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
---
2023-07-20 09:22:05,466 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: P:\automatic1111webui\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-20 09:22:05,561 - ControlNet - INFO - ControlNet v1.1.224
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [c0d1994c73] from P:\automatic1111webui\webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
*Deforum ControlNet support: enabled*
Creating model from config: P:\automatic1111webui\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
COMMANDLINE_ARGS does not contain --api, API won't be mounted.
Startup time: 10.7s (import torch: 1.7s, import gradio: 1.3s, import ldm: 0.4s, other imports: 1.0s, load scripts: 2.9s, create ui: 2.1s, gradio launch: 1.2s).
*** Failed reading extension data from Git repository (clip-interrogator-ext)
    Traceback (most recent call last):
      File "P:\automatic1111webui\webui\modules\extensions.py", line 62, in do_read_info_from_repo
        self.remote = next(repo.remote().urls, None)
      File "P:\automatic1111webui\system\python\lib\site-packages\git\repo\base.py", line 414, in remote
        raise ValueError("Remote named '%s' didn't exist" % name)
    ValueError: Remote named 'origin' didn't exist

---
*** Failed reading extension data from Git repository (sd-webui-controlnet)
    Traceback (most recent call last):
      File "P:\automatic1111webui\webui\modules\extensions.py", line 62, in do_read_info_from_repo
        self.remote = next(repo.remote().urls, None)
      File "P:\automatic1111webui\system\python\lib\site-packages\git\repo\base.py", line 414, in remote
        raise ValueError("Remote named '%s' didn't exist" % name)
    ValueError: Remote named 'origin' didn't exist

---
*** Failed reading extension data from Git repository (seed_travel)
    Traceback (most recent call last):
      File "P:\automatic1111webui\webui\modules\extensions.py", line 62, in do_read_info_from_repo
        self.remote = next(repo.remote().urls, None)
      File "P:\automatic1111webui\system\python\lib\site-packages\git\repo\base.py", line 414, in remote
        raise ValueError("Remote named '%s' didn't exist" % name)
    ValueError: Remote named 'origin' didn't exist

---
*** Failed reading extension data from Git repository (stable-diffusion-webui-images-browser)
    Traceback (most recent call last):
      File "P:\automatic1111webui\webui\modules\extensions.py", line 62, in do_read_info_from_repo
        self.remote = next(repo.remote().urls, None)
      File "P:\automatic1111webui\system\python\lib\site-packages\git\repo\base.py", line 414, in remote
        raise ValueError("Remote named '%s' didn't exist" % name)
    ValueError: Remote named 'origin' didn't exist

---
*** Failed reading extension data from Git repository (stable-diffusion-webui-rembg)
    Traceback (most recent call last):
      File "P:\automatic1111webui\webui\modules\extensions.py", line 62, in do_read_info_from_repo
        self.remote = next(repo.remote().urls, None)
      File "P:\automatic1111webui\system\python\lib\site-packages\git\repo\base.py", line 414, in remote
        raise ValueError("Remote named '%s' didn't exist" % name)
    ValueError: Remote named 'origin' didn't exist

---
preload_extensions_git_metadata for 25 extensions took 2.20s
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 5.7s (load weights from disk: 1.5s, create model: 0.7s, apply weights to model: 1.6s, apply half(): 0.7s, move model to device: 1.2s).
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.78it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.38it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.57it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.49it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.19it/s]
```

### Console logs

```Shell
Failed to load resource: the server responded with a status of 404 (Not Found)
:7860/favicon.ico:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
127.0.0.1/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
3canvas-zoom.js?1689829204.6660552:1186 work
```

**Comment by solyaevwork** [comment]
same(

**Comment by rbychn** [comment]
had the same issue, you need to update to the latest 1111 webUI version > 1.41

**Comment by salva133** [comment]
> had the same issue, you need to update to the latest 1111 webUI version > 1.41
> 
> you need to have the models downloaded and put in the correct folder and also remove or disable some other extension that might be causing compatibility issues with animatediff

What is the correct folder?!

**Comment by continue-revolution** [comment]
@TiagoSantos81 No you don’t, at least in A1111. I replaced batch size with frame number internally. You can set batch size to whatever number and it won’t have any effect. I’m not sure about vlad because I don’t use vlad.

**Comment by TiagoSantos81** [comment]
In Vlad it does. But the results I am getting are odd. It seems to be just sequential seeds being made into an animated gif, as in the example below, done with deliberate_v2. However, it doesn't throw exceptions on subsequent generations.

![00001-1047513503](https://github.com/continue-revolution/sd-webui-animatediff/assets/22968614/63e3fe28-6a7a-4604-94b7-2c1b75c35d8a)

I have yet to try with different memory optimization settings before filling and issue report.

**Comment by continue-revolution** [comment]
@TiagoSantos81 I highly recommend going back to A1111. I do not anticipate supporting vlad in foreseeable future. A1111 is currently actively maintaining and updating.

**Comment by lastYoueven** [comment]
i got same issus but i used animatediff gen some gif image and i install deforum, animatediff is not work! it gen the text2img without the Animatediff gif.
