### ISSUE TITLE
[Bug]:  match ip_adapter_key: ^     SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by davedaverave** [continue-revolution/sd-webui-animatediff#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I have installed animatediff on AUTOMATIC111 and once i run automatic i got this error: *** Error loading script: animatediff.py
I'm on a paperspace notebook, and unfortunatly i can't access this blessing of an addon!

I tryed to make a new notebook, and have a fresh start .. Python 3.9.16
Thanks, regard, Davide

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

That the addon would have loaded correctly and i could make my art with that wonderfull addon

### Commit where the problem happens

webui: Automatic1111
extension: default

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
!python launch.py --share --enable-insecure-extension-access --config ~/../datasets/stable-diffusion-classic-v2/768-v-ema.yaml --ckpt ~/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
```

### Console logs

```Shell
/notebooks/stable-diffusion-webui
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --share --enable-insecure-extension-access --config /root/../datasets/stable-diffusion-classic-v2/768-v-ema.yaml --ckpt /root/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 9, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 85
        match ip_adapter_key:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 846, in exec_module
      File "<frozen importlib._bootstrap_external>", line 983, in get_code
      File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 85
        match ip_adapter_key:
              ^
    SyntaxError: invalid syntax

---
Loading weights [bfcaf07557] from /root/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://23c8b9d641457ad665.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Startup time: 16.7s (prepare environment: 2.4s, import torch: 7.3s, import gradio: 1.1s, setup paths: 0.6s, initialize shared: 0.3s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 1.4s, create ui: 1.0s, gradio launch: 2.0s).
Creating model from config: /root/../datasets/stable-diffusion-classic-v2/768-v-ema.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 10.5s (load weights from disk: 5.1s, create model: 0.1s, apply weights to model: 4.5s, calculate empty prompt: 0.5s).
```

**Comment by continue-revolution** [comment]
This is because match case is introduced in Python 3.10 but I did not realize this when I developed this. I will fix this in 2 days.
