### ISSUE TITLE
[Bug]: Can't save as MP4

### ISSUE THREAD

**Issue by yamatazen** [continue-revolution/sd-webui-animatediff#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

An empty MP4 file was saved

### Steps to reproduce the problem

Generate an animation and save as MP4

### What should have happened?

A MP4 file

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--no-half-vae
```

### Console logs

```Shell
*** Error running postprocess: C:\Users\yamat\Desktop\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 76, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 35, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 178, in _save
        imageio.imwrite(video_path_mp4, video_array, fps=params.fps, codec="h264")
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\venv\lib\site-packages\imageio\v3.py", line 147, in imwrite
        encoded = img_file.write(image, **kwargs)
      File "C:\Users\yamat\Desktop\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\tifffile_v3.py", line 224, in write
        self._fh.write(image, **kwargs)
    TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

---
```

**Comment by continue-revolution** [comment]
#98

**Comment by yamatazen** [comment]
Why is not ffmpeg installed?
