### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by clcc1993** [continue-revolution/sd-webui-animatediff#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 15, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

webui

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 15, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
```

### Console logs

```Shell
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 15, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
```

**Comment by continue-revolution** [comment]
Search before ask
