### ISSUE TITLE
Search before ask / 先搜索再提问

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#204]
If your issue was closed without any response, it is because your question has answered before. Please cherish the developer’s time, in the way that you make good use of GitHub issue filter by removing “is:issue is:open” and search before asking question. Many questions have been resolved previously. If you search for “TORCH_USE_CUDA_DSA”, you will find 12 issues, which is really too overwhelming. I will not be your redirector anymore.

如果我没有回复就关闭你的issue，这是因为你的问题已经被回答过了。请善用issue搜索功能，先搜索再提问，把“is:issue is:open” 删除后搜索关键词，以节约我的时间。很多问题早已被回答过。如果你搜索“TORCH_USE_CUDA_DSA”，你会发现12条issue，令我不胜其扰。我不会再提供重定向服务。

**Comment by fish-lxh** [comment]
Error running postprocess: D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py", line 82, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'

**Comment by fish-lxh** [comment]
Error running before_process: D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py", line 50, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 58, in inject
        self._load(model_name)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 41, in _load
        mm_state_dict = sd_models.read_state_dict(model_path)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\sd_models.py", line 301, in read_state_dict
        sd = get_state_dict_from_checkpoint(pl_sd)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
        pl_sd = pl_sd.pop("state_dict", pl_sd)
    AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by fish-lxh** [comment]
Error running postprocess_batch_list: D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\extensions\sd-webui-animatediff\scripts\animatediff.py", line 70, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

**Comment by fish-lxh** [comment]
这些问题怎么解决？

**Comment by continue-revolution** [comment]
pytorch太老旧 / 没有下载模型 / WebUI太老旧，我只支持torch >= 2.0.0和WebUI >= 1.6.0，你需要手动下载模型。另外不要在这里提问

**Comment by fish-lxh** [comment]
好的



---原始邮件---
发件人: "Chengsong ***@***.***&gt;
发送时间: 2023年11月17日(周五) 上午10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [continue-revolution/sd-webui-animatediff] Search before ask / 先搜索再提问 (Issue #204)




 
@fish-lxh pytorch太老旧 / 没有下载模型 / WebUI太老旧，我只支持torch &gt;= 2.0.0和WebUI &gt;= 1.6.0，你需要手动下载模型。另外不要在这里提问

**Comment by fish-lxh** [comment]
老大，这个下面是什么原因，

raise NansException(message) modules.devices.NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
