### ISSUE TITLE
[Bug]: CUDA ERROR causes auto1111 not to work

### ISSUE THREAD

**Issue by ace2duce** [continue-revolution/sd-webui-animatediff#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

It should be able to do more than 400 frames with CLI I was able to do 1000. Also a CUDA error shouldn't completely stop auto1111

### Steps to reproduce the problem

1. Go to .... prompnt more than 400 frames or causes a CUDA error watch auto not recover

### What should have happened?

webui: v1.6.0
extension:  c1b6c4c9
CN : v1.1.410
![Desktop Screenshot 2023 10 11 - 16 17 18 49](https://github.com/continue-revolution/sd-webui-animatediff/assets/102707135/cc995c22-e506-4e3b-aff1-8ca0856395fa)

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
2023-10-11 16:03:23,266 - AnimateDiff - INFO - You are using mm_sd_v15_v2.ckpt, which has been tested and supported.
2023-10-11 16:03:23,279 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2023-10-11 16:03:23,279 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2023-10-11 16:03:23,279 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2023-10-11 16:03:23,280 - AnimateDiff - INFO - Setting DDIM alpha.
2023-10-11 16:03:23,282 - AnimateDiff - INFO - Injection finished.
2023-10-11 16:03:23,282 - AnimateDiff - INFO - Hacking lora to support motion lora
2023-10-11 16:03:23,282 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2023-10-11 16:03:23,283 - AnimateDiff - INFO - Hacking ControlNet.
2023-10-11 16:03:23,283 - AnimateDiff - INFO - You are using prompt travel.
  5%|████▏                                                                              | 1/20 [01:18<24:50, 78.47s/it]
*** Error completing request                                                                    | 0/20 [00:00<?, ?it/s]
*** Arguments: ('task(455ig62kwtcu61u)', '0: Close up of a Red Cyborg t\n100: Close up of a Blue Cyborg\n200: Close up of a Yellow Cyborg\n300: Close up of a Purple Cyborg\n400: Close up of a Green Cyborg', 'Women, man, Children', [], 20, 'DPM++ 2M SDE Heun Exponential', 1, 1, 6.5, 512, 832, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000190225E1210>, 0, False, '', 0.8, 315138839, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x00000190225E1390>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019000294FD0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019000104400>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000190001041F0>, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Auto1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Auto1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Auto1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 108, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Auto1111\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 258, in mm_cfg_forward
        x_out[a:b] = mm_sd_forward(self, x_in[a:b], sigma_in[a:b], subscript_cond(cond_in, a, b), subscript_cond(image_cond_in, a, b), make_condition_dict) # hook
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 167, in mm_sd_forward
        out = self.inner_model(x_in[_context], sigma_in[_context], cond=make_condition_dict(cond_in[_context], image_cond_in[_context]))
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 86, in mm_tes_forward
        x = layer(x, context)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 274, in _forward
        x = self.ff(self.norm3(x)) + x
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 76, in forward
        return self.net(x)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "C:\Auto1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Auto1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 56, in forward
        return x * F.gelu(gate)
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 260.00 MiB (GPU 0; 12.00 GiB total capacity; 9.73 GiB already allocated; 0 bytes free; 11.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---
2023-10-11 16:15:31,102 - AnimateDiff - INFO - You are using prompt travel.
*** Error completing request
*** Arguments: ('task(jgo1kuv5xm4kht4)', '0: Close up of a Red Cyborg spinning in a commercial parallaxing movement\n100: Close up of a Blue Cyborg spinning in a commercial parallaxing movement\n200: Close up of a Yellow Cyborg spinning  in a commercial parallaxing movement\n300: Close up of a Purple Cyborg spinning  in a commercial parallaxing movement\n400: Close up of a Green Cyborg spinning  in a commercial parallaxing movement', 'Women, man, Children', [], 20, 'DPM++ 2M SDE Heun Exponential', 1, 1, 6.5, 832, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001902258B160>, 0, False, '', 0.8, 315138839, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000019022589030>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000190225E0D60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000190225E05B0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001902258A2C0>, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Auto1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Auto1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Auto1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Auto1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 107, in hacked_processing_process_images_hijack
        prompt_scheduler.parse_prompt(p)
      File "C:\Auto1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 60, in parse_prompt
        assert len(prompt_list) == p.batch_size, f"prompt_list length {len(prompt_list)} != batch_size {p.batch_size}"
    AssertionError: prompt_list length 400 != batch_size 1
```

### Additional information

N/A

**Comment by continue-revolution** [comment]
If you OOM, you will have to re-start, otherwise the injection won’t work properly. There is no get-around unfortunately. The OOM is a separate problem which I will investigate later.

**Comment by ace2duce** [comment]
ok, thanks

**Comment by ace2duce** [comment]
> If you OOM, you will have to re-start, otherwise the injection won’t work properly. There is no get-around unfortunately. The OOM is a separate problem which I will investigate later.

Just so you know, I'm seeing the dedicated memory stay about 80% of my Vram and not releasing it. I can run animateDiff prompt traveler once and then I have to restart after the OOM. Is that a memory leak? I even tried to unload SD model to free up memory, However the OOF still happens. Thanks for all your hard work.
