### ISSUE TITLE
[Feature]: how to solve this Issue

### ISSUE THREAD

**Issue by qq7286590** [continue-revolution/sd-webui-animatediff#214]
### Expected behavior

run the webUI  wrong,
*** Error loading script: animate.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd-webui-aki-v4.4\extensions\AnimateDiff001\scripts\animate.py", line 15, in <module>
        from animatediff.models.unet import UNet3DConditionModel
      File "E:\sd-webui-aki-v4.4\extensions\AnimateDiff001\animatediff\models\unet.py", line 15, in <module>
        from diffusers.modeling_utils import ModelMixin
    ModuleNotFoundError: No module named 'diffusers.modeling_utils'

**Comment by continue-revolution** [comment]
You are installing the original repo, not this extension.

**Comment by qq7286590** [comment]
用的是别人打包的一键包，之前没出现过这种情况

**Comment by yuno779** [comment]
> 用的是别人打包的一键包，之前没出现过这种情况

祝你身体健康

**Comment by qq7286590** [comment]
> You are installing the original repo, not this extension.

Thanks for your reply, ,already running the program perfectly

**Comment by STLOONG** [comment]
> > You are installing the original repo, not this extension.
> 
> Thanks for your reply, ,already running the program perfectly
请问是怎么解决的
