### ISSUE TITLE
[Bug]: cannot generate the animation 

### ISSUE THREAD

**Issue by kiingroup** [continue-revolution/sd-webui-animatediff#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

error to create the animation gif

### Steps to reproduce the problem

1. Go to txt2img, fill the wordings
2. fill the request at AnimateDiff
3. then "Generate"

### What should have happened?

created the animation gif

### Commit where the problem happens

webui: v1.6.0
python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2 
extension: 

### Command Line Arguments

```Shell
2023-10-14 07:57:48,826 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
2023-10-14 07:57:48,827 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
File D:\Git\stable-diffusion-webui\extensions\stable-diffusion-webui-wildcards\wildcards\girl.txt not found for the __girl__ wildcard.
*** Error running before_process_batch: D:\Git\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\Git\stable-diffusion-webui\modules\scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
    TypeError: AnimateDiffScript.before_process_batch() missing 1 required positional argument: 'params'

---
*** Error running process_batch: D:\Git\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "D:\Git\stable-diffusion-webui\modules\scripts.py", line 643, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "D:\Git\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 169, in process_batch
        if not args[0]:
    IndexError: tuple index out of range

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.24it/s]
*** Error running postprocess: D:\Git\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.pyt/s]
    Traceback (most recent call last):
      File "D:\Git\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: AnimateDiffScript.postprocess() missing 1 required positional argument: 'params'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.30it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  7.82it/s]
```

### Console logs

```Shell
Failed to load resource: the server responded with a status of 404 (Not Found):7860/openpose_editor_index:1
```

**Comment by continue-revolution** [comment]
I believe that sd-webui-additional-networks is no longer needed. Please try to remove that and re-try.

**Comment by kiingroup** [comment]
tested, coz crashed with the extension "SD-CN-Animation", when i removed then Animatediff is work!

thanks.
