### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by michaeltran33** [continue-revolution/sd-webui-animatediff#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

doesnt work at all in img2img, 
"*** Error running postprocess: D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: AnimateDiffScript.postprocess() missing 1 required positional argument: 'params'"

### Steps to reproduce the problem

1. sent img to img2img
2. enable animetediff
3. generated - nothing 

### What should have happened?

gif generated

### Commit where the problem happens

webui: version: [v1.6.0]  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [f90fa41d65]
extension: animatediff - f89913c4

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --medvram --api --no-half-vae
```

### Console logs

```Shell
*** Error running postprocess: D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: AnimateDiffScript.postprocess() missing 1 required positional argument: 'params'
```

**Comment by michaeltran33** [comment]
found that it does work with mov2mov, turned mov2mov off, it it works fine.
