### ISSUE TITLE
[Bug]: After updating to AnimateDiff v1.10.0, I can no longer perform batch processing in img2img when AnimateDiff is not in use.

### ISSUE THREAD

**Issue by ai-is-in-wonderland** [continue-revolution/sd-webui-animatediff#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

After updating to AnimateDiff v1.10.0, I can no longer perform batch processing in img2img when AnimateDiff is not in use.

RuntimeError: bad number of images passed: 25; expecting 1 or less
Time taken: 0.2 sec.

 AnimateDiff - INFO - [i2i batch] Will process 25 images, creating 1 new videos.
*** Error completing request
        raise RuntimeError(f"bad number of images passed: {len(imgs)}; expecting {self.batch_size} or less")
    RuntimeError: bad number of images passed: 25; expecting 1 or less

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Batch processing in img2img works as expected when AnimateDiff is not in use.

### Commit where the problem happens

webui: img2img batch
extension: 

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
2023-10-29 09:27:46,770 - AnimateDiff - INFO - [i2i batch] Will process 25 images, creating 1 new videos.
*** Error completing request
*** Arguments: ('task(cnm9u5ijo19uiaf)', 5, '', '', [], None, None, None, None, None, None, None, 20, 'Euler a', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 0, 512, 512, 1, 0, 0, 32, 0, 'C:\\stable-diffusion-webui\\outputs\\txt2img-images\\2023-10-29\\4', 'C:\\stable-diffusion-webui\\outputs\\txt2img-images\\2023-10-29\\4-up2', '', [], False, [], '', <gradio.routes.Request object at 0x0000029EB4D7F460>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000029EB4D7E680>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC688B80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC6880A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC68B2E0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC689DE0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EB4D7E590>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC6892A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC6886D0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EBC68AF80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EB4D7EA40>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000029EB4D7F190>, False, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, '', False, 'Normal', 1, True, 1, 1, 'None', False, False, False, 'YuNet', 512, 1024, 0.5, 1.5, False, 'face close up,', 0.5, 0.5, False, True, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\stablediffusion20230811\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\stablediffusion20230811\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\stablediffusion20230811\stable-diffusion-webui\modules\img2img.py", line 202, in img2img
        process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 280, in hacked_img2img_process_batch_hijack
        process_images(p)
      File "C:\stablediffusion20230811\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
```

**Comment by continue-revolution** [comment]
I forgot to do another check. I will fix it soon.

**Comment by ai-is-in-wonderland** [comment]
Thank you for your prompt response
