### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by navarisun1982** [continue-revolution/sd-webui-animatediff#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I have this error on a clean installation of automatic1111 1.6 and the latest version of animatediff as of today, i also have ffmpeg successfully installed

can this be fixed ?

### Steps to reproduce the problem

on the start of stable diffusion

### What should have happened?

it should work as i followed all the steps

### Commit where the problem happens

webui: 1.6
extension: master | 4a5461ee

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### Console logs

```Shell
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 16, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 4, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
```

**Comment by continue-revolution** [comment]
Search before ask.

**Comment by scofi** [comment]
我解决了这个问题，原因是imageio版本太老了，你先删除再安装或者升级
pip uninstall imageio 
再执行
pip install imageio
