### ISSUE TITLE
[Bug]: Nonetype error. 

### ISSUE THREAD

**Issue by Rainbrine** [continue-revolution/sd-webui-animatediff#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Getting an odd issue whenever I run the animatediff.

it will give me a log error whenever I run the extension. The error causes a gif to not generate, and for a grid of images to take it's place. 

### Steps to reproduce the problem

I've installed the addon and everything appears to work as intended. It runs with animatediff turned on but does not produce a gif- just a collection of images. 
![Capture](https://github.com/continue-revolution/sd-webui-animatediff/assets/108708301/9446d75e-edaf-43e5-b49d-8cdd394da445)

I'm using OperaGX.

### What should have happened?

The output should have been a gif, but instead, I was given a collection of images. 

### Commit where the problem happens

webui: Latest version of the webUI. 
extension: [37b7b58a]

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --medvram --autolaunch --xformers
```

### Console logs

```Shell
There are two errors that appear in the console. I will post both. 

This error appears upon booting up the webui:
====================================================================

*** Error running before_process: D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\rentry\NewUI\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 49, in inject
        self._load(model_name)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 40, in _load
        missed_keys = self.mm.load_state_dict(mm_state_dict)
      File "D:\rentry\NewUI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for MotionWrapper:
        Missing key(s) in state_dict: "down_blocks.0.motion_modules.0.temporal_transformer.norm.weight", "
====================================================================
This error appears upon completing a generated image with animatediff enabled:

*** Error running postprocess_batch_list: D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py████████████████████████████████████████████████████████████████▍    | 39/40 [00:08<00:00, 14.05it/s]
    Traceback (most recent call last):
      File "D:\rentry\NewUI\stable-diffusion-webui\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 71, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\rentry\NewUI\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 83, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
```

**Comment by continue-revolution** [comment]
You are not using motion Lora in the correct way. Recall how you use ordinary Lora.

**Comment by Rainbrine** [comment]
> You are not using motion Lora in the correct way. Recall how you use ordinary Lora.

Despite using the lora how I would use a normal Lora, I get the same result.

\animatediff.py
    Traceback (most recent call last):
      File "D:\rentry\NewUI\stable-diffusion-webui\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 71, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\rentry\NewUI\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\rentry\NewUI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 83, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
![Capture](https://github.com/continue-revolution/sd-webui-animatediff/assets/108708301/378ca08e-fb20-43cb-9c3a-48b928eaaf3e)

**Comment by continue-revolution** [comment]
You are still using AnimateDiff in the wrong way. You need to choose a motion module instead of motion lora

**Comment by Rainbrine** [comment]
@continue-revolution > You are still using AnimateDiff in the wrong way. You need to choose a motion module instead of motion lora

Ah, I see now... but whenever I try to create something, not it just won't generate. I'll attach a screenshot of what I mean, as well as the parameters I used. 

Thank you again for responding!
![12](https://github.com/continue-revolution/sd-webui-animatediff/assets/108708301/dc80ddaf-15fa-4cb0-af00-afb6de4e3561)
![Capture](https://github.com/continue-revolution/sd-webui-animatediff/assets/108708301/dec83fb2-79e7-40ac-8f68-e018d645017b)

**Comment by continue-revolution** [comment]
You don't have enough vram. Enable one of `--xformers` and `--opt-sdp-attention` and see how things go
