### ISSUE TITLE
[Bug]: Possibly unable to find animation models? (DirectML WebUI)

### ISSUE THREAD

**Issue by oatmealformana** [continue-revolution/sd-webui-animatediff#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Whenever I try to generate anything, produces an error message, then creates 16 totally different images and puts them together in a 8fps slideshow. It does not animate it. I believe that is because it cannot find the motion modules.

### Steps to reproduce the problem

1. Launch WebUI
2. Enable AnimateDiff
3. Make sure the modules are in the right path (D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\model\mm_sd_v15.ckpt)
4. Generate animation
5. Failure

### What should have happened?

Even though it did not work this time, it should have animated it, and not produced the error message.

### Commit where the problem happens

webui: commit [089a002](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/089a0022ae9dd53c7b9b540e251fb0231459e297)
extension: [287b30af](https://github.com/continue-revolution/sd-webui-animatediff/commit/287b30afc3d111c39676fab38bf79adda3c715b3)

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--medvram --theme dark
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
set OPTIMIZED_TURBO=true

call webui.bat
```

### Console logs

```Shell
2023-07-24 13:13:32,058 - AnimateDiff - INFO - Loading motion module mm_sd_v15.ckpt from D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\model\mm_sd_v15.ckpt
*** Error running before_process: D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\scripts.py", line 466, in before_process
        script.before_process(p, *script_args)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\scripts\animatediff.py", line 128, in before_process
        self.inject_motion_modules(p, model)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\scripts\animatediff.py", line 79, in inject_motion_modules
        mm_state_dict = torch.load(model_path, map_location=device)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 809, in load
        return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
        result = unpickler.load()
      File "C:\Users\fungus\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\fungus\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1254, in load_binpersid
        self.append(self.persistent_load(pid))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
        typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
        wrap_storage=restore_location(storage, location),
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1086, in restore_location
        return default_restore_location(storage, str(map_location))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 220, in default_restore_location
        raise RuntimeError("don't know how to restore data location of "
    RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with privateuseone:0)

---
  0%|                                                                                           | 0/20 [00:01<?, ?it/s]
*** Error completing request
*** Arguments: ('task(5ngtapseuwup5ra)', 'by zackary911, (salazzle, pokemon, anthro), scalie, scales, [female|ambiguous gender], (girly:1.3), (muscular:0.3), [musclegut, slightly chubby, overweight:8], flat chest, moobs, blowjob', 'hair,deformed,ugly,blurry,bad anatomy,disfigured,extra limb,deformed hands,deformed feet,face out of frame,multiple tails,((bad anatomy)),disfigured,deformed,malformed,mutant,monstrous,ugly,gross,disgusting,blurry,poorly drawn,extra limbs,extra fingers,missing limbs,amputee,malformed hands,multi balls,multi penis,floating penis,dialogue,text,deformed face,hair,cub,child, (((3 toes, 5 toes)))', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 256, 256, False, 0.75, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, 0, False, 0, False, False, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', True, 0, 8, 4, 'mm_sd_v15.ckpt', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\processing.py", line 623, in process_images
        res = process_images_inner(p)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\processing.py", line 742, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\processing.py", line 995, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 439, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 439, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 177, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 802, in forward
        h = module(h, emb, context)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\extensions\sd-webui-animatediff\scripts\animatediff.py", line 25, in mm_tes_forward
        x = layer(x)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\AI shit\A1111 Web UI Autoinstaller\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 109, in forward
        assert x.shape[1] == self.channels
    AssertionError

---
```

### Additional information

The second error, the AssertionError, happens after a second failed generation.

**Comment by FatalErrorVXD** [comment]
Nevermind it looks like my ckpt was corrupted somehow.

**Comment by socom20** [comment]
same problem

**Comment by lanyan520** [comment]
Update version to 1.5（sd）, the problem is solved, as to how to solve I am not clear

> same problem

**Comment by continue-revolution** [comment]
you must update A1111 to 1.6.0 to use this extension

**Comment by zuriher123** [comment]
2023-10-19 11:09:57,725 - AnimateDiff - INFO - Injecting motion module mm_sd_v15.ckpt into SD1.5 UNet input blocks.
*** Error running before_process: E:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 50, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 109, in inject
        unet.input_blocks[unet_idx].append(
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\container.py", line 295, in __getitem__
        return self._modules[self._get_abs_string_index(idx)]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\container.py", line 285, in _get_abs_string_index
        raise IndexError('index {} is out of range'.format(idx))
    IndexError: index 10 is out of range
