### ISSUE TITLE
Not Working with ControlNet

### ISSUE THREAD

**Issue by MaximumBlast** [continue-revolution/sd-webui-animatediff#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I get this error when running AnimateDiff:

2023-11-14 00:49:37,108 - AnimateDiff - INFO - Hacking ControlNet.
*** Error running before_process: C:\Users\mp\Documents\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\mp\Documents\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "C:\Users\mp\Documents\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 57, in before_process
        self.cn_hacker.hack(params)
      File "C:\Users\mp\Documents\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 626, in hack
        self.hack_cn()
      File "C:\Users\mp\Documents\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 609, in hack_cn
        AnimateDiffControl.original_controlnet_main_entry = self.cn_script.controlnet_main_entry
    AttributeError: 'Script' object has no attribute 'controlnet_main_entry'
    
    
    I't wont work with Controlnet. It outouts:
    
    
   ImportError: cannot import name 'ControlModelType' from 'scripts.hook' (C:\Users\mp\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py)
    
    
    Any ideas?
    
    

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Should work with ControNet

### Commit where the problem happens

webui: AUTO1111
extension: AnimateDif

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --xformers --autolaunch --update-check
```

### Console logs

```Shell
see above
```

**Comment by continue-revolution** [comment]
your ControlNet is probably too outdated. Please update.

**Comment by MaximumBlast** [comment]
Yes, it was up to date, but only a full reinstall of Controlnet fixed the problem, thank you.
