### ISSUE TITLE
[Bug]: Only rendering a single stitch without forming a film

### ISSUE THREAD

**Issue by designrans** [continue-revolution/sd-webui-animatediff#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

<img width="1569" alt="1699931844873" src="https://github.com/continue-revolution/sd-webui-animatediff/assets/130264837/67f93848-baf3-4255-b076-9a087785efd3">

### Steps to reproduce the problem

*** Error running postprocess: C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.4\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 82, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

### What should have happened?

Only rendering a single stitch without forming a film

### Commit where the problem happens

webui: 1.61
extension: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--disable-safe-unpickle
```

### Console logs

```Shell
refresh_ui
Model loaded in 12.0s (load weights from disk: 2.0s, create model: 1.7s, apply weights to model: 7.3s, move model to device: 0.2s, load textual inversion embeddings: 0.3s, calculate empty prompt: 0.4s).
2023-11-14 11:16:30,126 - AnimateDiff - INFO - AnimateDiff process start.
2023-11-14 11:16:30,126 - AnimateDiff - INFO - Loading motion module mm_sdxl_v10_beta.ckpt from C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\model\mm_sdxl_v10_beta.ckpt
*** Error verifying pickled file from C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\model\mm_sdxl_v10_beta.ckpt
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
*** 
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.4\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "C:\sd-webui-aki-v4.4\modules\safe.py", line 84, in check_pt
        check_zip_filenames(filename, z.namelist())
      File "C:\sd-webui-aki-v4.4\modules\safe.py", line 76, in check_zip_filenames
        raise Exception(f"bad file inside {filename}: {name}")
    Exception: bad file inside C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\model\mm_sdxl_v10_beta.ckpt: mm_sdxl_nightly,ckpt/byteorder
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running before_process: C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.4\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 50, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 58, in inject
        self._load(model_name)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 41, in _load
        mm_state_dict = sd_models.read_state_dict(model_path)
      File "C:\sd-webui-aki-v4.4\modules\sd_models.py", line 301, in read_state_dict
        sd = get_state_dict_from_checkpoint(pl_sd)
      File "C:\sd-webui-aki-v4.4\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
        pl_sd = pl_sd.pop("state_dict", pl_sd)
    AttributeError: 'NoneType' object has no attribute 'pop'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
purged
==========================================================================================
A tensor with all NaNs was produced in VAE.
Web UI will now convert VAE into 32-bit float and retry.
To disable this behavior, disable the 'Automatically revert VAE to 32-bit floats' setting.
To always start with 32-bit VAE, use --no-half-vae commandline flag.
==========================================================================================
*** Error running postprocess_batch_list: C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.4\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 70, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.4\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 82, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
```

**Comment by continue-revolution** [comment]
You failed to add command line arg --disable-safe-unpickle. Unfortunately, I have no idea about the package from Akegarasu. You need to figure out on your own.

**Comment by wfjsw** [comment]
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/2220320/086a3a7a-aa40-4020-b8af-7eb8fc4c4b4d)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/2220320/207ce68a-bf79-4a51-ba93-3326cb61aeed)

**Comment by continue-revolution** [comment]
For people who use Akegarasu's package, please refer to the images above.

秋叶整合包用户请参考上图
