### ISSUE TITLE
[Bug]: Video2Video crashes corntlnet 

### ISSUE THREAD

**Issue by IoakeimSogiakas** [continue-revolution/sd-webui-animatediff#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I am trying to use a video as a source but controlnet crashes. It is asking for input but I thought (based on the instruction that I don't need to do that). Also if it matters it always just generates on image 

### Steps to reproduce the problem

1. Make a Prompt (both + and -)
2. Set the basic setting on animateDiff (basically turn it on since inputting the video auto-populates the fps)
3. Turn on CotnrolNet ( on this example I have used canny)
4. Hit generate.

### What should have happened?

The video should start generating

### Commit where the problem happens

webui: 5ef669de080814067961f28357256e8fe27544f4
extension: 777631d2e9497e433fb6fddbf29bfa9754af2a3f
ControlNet: c1f3d6f8505074d73b13eaf67f331bf869d7b940

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
On Colab  --gradio-img2img-tool color-sketch --enable-insecure-extension-access --gradio-queue --ngrok 2XuUJfw5ke22IMZzz3sZhev4Uc3_7Nrumn6vKMEkTfNCoBfRr  --gradio-auth a:a  --disable-model-loading-ram-optimization --opt-sdp-no-mem-attention

And on Local just --xformers but I have selected the second optimization method on the settings
```

### Console logs

```Shell
Model loaded in 72.6s (load weights from disk: 41.3s, create model: 1.4s, apply weights to model: 13.4s, apply half(): 1.2s, load VAE: 12.8s, move model to device: 0.6s, load textual inversion embeddings: 1.2s, calculate empty prompt: 0.7s).
2023-11-14 22:20:05,693 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
2023-11-14 22:20:12,752 - ControlNet - INFO - Loaded state_dict from [/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_canny.pth]
2023-11-14 22:20:12,753 - ControlNet - INFO - controlnet_default_config
2023-11-14 22:20:16,553 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
*** Error running process: /content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 981, in process
        self.controlnet_hack(p)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 970, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 696, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 608, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given

---
  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:02<00:44,  2.34s/it]
 15% 3/20 [00:02<00:11,  1.54it/s]
 20% 4/20 [00:02<00:07,  2.19it/s]
 25% 5/20 [00:02<00:05,  2.85it/s]
 30% 6/20 [00:03<00:04,  3.48it/s]
 35% 7/20 [00:03<00:03,  3.95it/s]
 40% 8/20 [00:03<00:02,  4.44it/s]
 45% 9/20 [00:03<00:02,  4.82it/s]
 50% 10/20 [00:03<00:01,  5.15it/s]
 55% 11/20 [00:03<00:01,  5.39it/s]
 60% 12/20 [00:04<00:01,  5.58it/s]
 65% 13/20 [00:04<00:01,  5.65it/s]
 70% 14/20 [00:04<00:01,  5.63it/s]
 75% 15/20 [00:04<00:00,  5.30it/s]
 80% 16/20 [00:05<00:00,  4.53it/s]
 85% 17/20 [00:05<00:00,  3.97it/s]
 90% 18/20 [00:05<00:00,  3.55it/s]
 95% 19/20 [00:06<00:00,  3.43it/s]
100% 20/20 [00:06<00:00,  3.07it/s]

Total progress: 100% 20/20 [00:07<00:00,  2.56it/s]
```

### Additional information

Using Both collab and Locally  (primarily due to GPU limitations)
also, I am using this controlNet repo if that matters
https://github.com/Mikubill/sd-webui-controlnet

**Comment by continue-revolution** [comment]
There is no log associated with AnimateDiff, which means that you did not enable AnimateDiff extension.

**Comment by IoakeimSogiakas** [comment]
That's my problem I have clearly enabled it. (I apologize for the wrong command line I did not  pay the appropriate tension when copying it).
I had gotten that error before but that might have been only on my local installation now I am getting a CUDA out of memory (collab has about 15 GB of vram) I have done what you suggested on a other issue for Cuda errors ( --no-half-vae, --opt-sdp-attention) but that has not helped 


`Total progress: 100% 20/20 [00:17<00:00,  1.12it/s]
2023-11-15 09:02:17,915 - AnimateDiff - INFO - AnimateDiff process start.
2023-11-15 09:02:17,916 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from /content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/model/mm_sd_v15_v2.ckpt
2023-11-15 09:02:27,681 - AnimateDiff - INFO - Guessed mm_sd_v15_v2.ckpt architecture: MotionModuleType.AnimateDiffV2
2023-11-15 09:02:34,229 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-11-15 09:02:34,846 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2023-11-15 09:02:34,846 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2023-11-15 09:02:34,846 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2023-11-15 09:02:34,847 - AnimateDiff - INFO - Setting DDIM alpha.
2023-11-15 09:02:34,878 - AnimateDiff - INFO - Injection finished.
2023-11-15 09:02:34,878 - AnimateDiff - INFO - Hacking loral to support motion lora
2023-11-15 09:02:34,878 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2023-11-15 09:02:34,878 - AnimateDiff - INFO - Hacking ControlNet.
2023-11-15 09:02:39,393 - ControlNet - INFO - Loading model: control_v11p_sd15_lineart [43d4be0d]
2023-11-15 09:03:05,182 - ControlNet - INFO - Loaded state_dict from [/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_lineart.pth]
2023-11-15 09:03:05,182 - ControlNet - INFO - controlnet_default_config
2023-11-15 09:03:08,994 - ControlNet - INFO - ControlNet model control_v11p_sd15_lineart [43d4be0d] loaded.
2023-11-15 09:03:11,213 - ControlNet - INFO - Loading preprocessor: lineart_standard
2023-11-15 09:03:11,213 - ControlNet - INFO - preprocessor resolution = 512
2023-11-15 09:03:17,509 - ControlNet - INFO - ControlNet Hooked - Time = 38.528281688690186
  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:52<16:29, 52.07s/it]
 10% 2/20 [01:36<14:31, 48.40s/it]
*** Error completing request
*** Arguments: ('task(ahog1ya1bllnxco)', 'photo of Sci fi girl, pink hair, photorealistic, in the style of franciszek starowieyski, white porcelain sci fi, mecha, 32k uhd, machine aesthetics, dark white and azure, hans zatzka, silver and pink, science fiction city,shiny pink hair, half body, oil painting, white background', 'deformed, disfigured, ugly', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x7e3e486dae00>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x7e3e9a2c9690>, UiControlNetUnit(enabled=True, module='lineart_standard (from white bg & black line)', model='control_v11p_sd15_lineart [43d4be0d]', weight=1, image=None, resize_mode='Crop and Resize', low_vram=True, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='Balanced', save_detected_map=True), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', [False], '0', '0', '0.4', None, '0', '0', False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, [], 30, '', 4, [], 1, '', '', '', '') {}
    Traceback (most recent call last):
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 118, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 451, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 250, in mm_cfg_forward
        x_out = mm_sd_forward(self, x_in, sigma_in, cond_in, image_cond_in, make_condition_dict) # hook
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 160, in mm_sd_forward
        out = self.inner_model(
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 858, in forward_webui
        raise e
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 855, in forward_webui
        return forward(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 762, in forward
        h = module(h, emb, context)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 86, in forward
        x = layer(x)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 112, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 178, in forward
        hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, video_length=video_length)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 248, in forward
        hidden_states = self.ff(self.ff_norm(hidden_states)) + hidden_states
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 76, in forward
        return self.net(x)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
        input = module(input)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/content/drive/MyDrive/AI_PICS/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 56, in forward
        return x * F.gelu(gate)
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 218.81 MiB is free. Process 485110 has 14.53 GiB memory in use. Of the allocated memory 13.56 GiB is allocated by PyTorch, and 835.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

`---`
[Stable Diffusion.pdf](https://github.com/continue-revolution/sd-webui-animatediff/files/13362386/Stable.Diffusion.pdf)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/74249861/45d941f4-bb3b-4573-b8ed-0ec0aa76f28f)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/74249861/31fad17c-3473-406b-a246-df60a3298f39)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/74249861/3983c4b2-5d8e-4dc4-b578-9b8bd04e5c7e)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/74249861/315b976a-6d36-4197-bdcb-49fa9df9d848)

**Comment by renmengyuan** [comment]
> I got the same problem with the recent installation.
> 
> ```
> 2023-11-15 15:56:18,495 - AnimateDiff - INFO - AnimateDiff process start.
> 2023-11-15 15:56:18,504 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
> 2023-11-15 15:56:18,504 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
> 2023-11-15 15:56:18,504 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
> 2023-11-15 15:56:18,504 - AnimateDiff - INFO - Setting DDIM alpha.
> 2023-11-15 15:56:18,507 - AnimateDiff - INFO - Injection finished.
> 2023-11-15 15:56:18,507 - AnimateDiff - INFO - Hacking loral to support motion lora
> 2023-11-15 15:56:18,507 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
> 2023-11-15 15:56:18,508 - AnimateDiff - INFO - Hacking ControlNet.
> 2023-11-15 15:56:21,188 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_lineart_fp16 [5c23b17d]
> *** Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
>     Traceback (most recent call last):
>       File "/content/stable-diffusion-webui/modules/scripts.py", line 619, in process
>         script.process(p, *script_args)
>       File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 981, in process
>         self.controlnet_hack(p)
>       File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 970, in controlnet_hack
>         self.controlnet_main_entry(p)
>       File "/content/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 260, in hacked_main_entry
>         input_image, image_from_a1111 = cn_script.choose_input_image(p, unit, idx)
>       File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 608, in choose_input_image
>         raise ValueError('controlnet is enabled but no input image is given')
>     ValueError: controlnet is enabled but no input image is given
> 
> ---
>   0%|                                                                                                                                                                     | 0/5 [00:00<?, ?it/s]
> Total progress:   0%|                                                                     20%|███████████████████████████████▍                                                                                                                             | 1/5 [00:12<00:49, 12.43s/it]
> Total progress:  40%|████████████████████████████████████████████████████████▍            40%|██████████████████████████████████████████████████████████████▊                                                                                              | 2/5 [00:24<00:37, 12.46s/it]
> Total progress:  60%|████████████████████████████████████████████████████████████████████ 60%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 3/5 [00:41<00:29, 14.54s/it]
> Total progress:  80%|████████████████████████████████████████████████████████████████████ 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 4/5 [00:57<00:15, 15.11s/it]
> Total progress: 100%|████████████████████████████████████████████████████████████████████100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [01:13<00:100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [01:13<00:00, 14.76s/it]
> 2023-11-15 15:57:55,045 - AnimateDiff - INFO - Restoring ControlNet.
> 2023-11-15 15:57:55,045 - AnimateDiff - INFO - Restoring CFGDenoiser forward function.
> 2023-11-15 15:57:55,045 - AnimateDiff - INFO - Restoring hacked lora
> 2023-11-15 15:57:55,045 - AnimateDiff - INFO - Restoring DDIM alpha.
> 2023-11-15 15:57:55,045 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
> 2023-11-15 15:57:55,046 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
> 2023-11-15 15:57:55,046 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
> 2023-11-15 15:57:55,046 - AnimateDiff - INFO - Removal finished.
> 2023-11-15 15:57:55,046 - AnimateDiff - INFO - Merging images into GIF.
> 2023-11-15 15:57:55,141 - AnimateDiff - INFO - AnimateDiff process end.
> ```

how did you fix this problem ?

**Comment by IoakeimSogiakas** [comment]
For me it fixed it self i was running it on colab which might have been the issue
