### ISSUE TITLE
[Bug]:   I get a collections of different image's base on the prompt instead of the gif.

### ISSUE THREAD

**Issue by FatalErrorVXD** [continue-revolution/sd-webui-animatediff#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I use the same positive, negative prompt and parameters from the exa,mple. Instead of getting motion, I get a collections of different image's base on the prompt instead of the gif. 

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/133708056/cf760828-d0ac-4d47-ac0d-0bdb227fc2fd)
![00002-7132772652786303](https://github.com/continue-revolution/sd-webui-animatediff/assets/133708056/9a285d6a-3843-4f4a-9844-5e5d641684c7)

### Steps to reproduce the problem

Run as usual

### What should have happened?

Generate a motion gif

### Commit where the problem happens

webui: latest
extension: latest

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --listen --api --no-half-vae --disable-nan-check --enable-insecure-extension-access 
call webui.bat
```

### Console logs

```Shell
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
preload_extensions_git_metadata for 18 extensions took 1.22s
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.9s (import torch: 1.7s, import gradio: 1.6s, import ldm: 0.5s, other imports: 0.9s, load scripts: 1.7s, create ui: 12.8s, gradio launch: 4.6s).
2023-07-24 16:01:10,724 - AnimateDiff - INFO - AnimateDiff process start with video Max frames 16, FPS 8, duration 2.0,  motion module mm_sd_v15.ckpt.
2023-07-24 16:01:10,724 - AnimateDiff - INFO - Loading motion module mm_sd_v15.ckpt from C:\Gits\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15.ckpt
*** Error verifying pickled file from C:\Gits\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15.ckpt
*** -----> !!!! The file is most likely corrupted !!!! <-----
*** You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.
***
    Traceback (most recent call last):
      File "C:\Gits\stable-diffusion-webui\modules\safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "C:\Gits\anaconda3\lib\zipfile.py", line 1269, in __init__
        self._RealGetContents()
      File "C:\Gits\anaconda3\lib\zipfile.py", line 1336, in _RealGetContents
        raise BadZipFile("File is not a zip file")
    zipfile.BadZipFile: File is not a zip file

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Gits\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "C:\Gits\stable-diffusion-webui\modules\safe.py", line 104, in check_pt
        unpickler.load()
    _pickle.UnpicklingError: invalid load key, '<'.

---
*** Error running before_process: C:\Gits\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Gits\stable-diffusion-webui\modules\scripts.py", line 466, in before_process
        script.before_process(p, *script_args)
      File "C:\Gits\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 116, in before_process
        self.inject_motion_modules(p, model)
      File "C:\Gits\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 78, in inject_motion_modules
        missed_keys = AnimateDiffScript.motion_module.load_state_dict(mm_state_dict)
      File "C:\Gits\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict
        raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
    TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.12it/s]
2023-07-24 16:01:37,268 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.███████████████████████████████████████████████████████████████████████████████| 20/20 [00:16<00:00,  1.18it/s]
2023-07-24 16:01:37,268 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-07-24 16:01:37,268 - AnimateDiff - INFO - Removal finished.
2023-07-24 16:01:37,269 - AnimateDiff - INFO - Merging images into GIF.
2023-07-24 16:01:38,818 - AnimateDiff - INFO - AnimateDiff process end.
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.21s/it]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.18it/s]
```

**Comment by FatalErrorVXD** [comment]
Nevermind. Ckpt was corrupted. Downloaded it again, and it worked.

**Comment by FatalErrorVXD** [comment]
Nevermind. Ckpt was corrupted. Downloaded it again, and it worked.
