### ISSUE TITLE
[Bug]: plugin incompatible with mm_sdxl_v10_beta model

### ISSUE THREAD

**Issue by fuxiocteract** [continue-revolution/sd-webui-animatediff#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

after running sdxl beta model, with latest sd-webui-animatediff plugin, with automatic1111 web ui 1.9, enabled animatediff, and generate, the log shows:

*** Error running before_process: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 60, in inject
        self._load(model_name)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 41, in _load
        mm_state_dict = sd_models.read_state_dict(model_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\sd_models.py", line 301, in read_state_dict
        sd = get_state_dict_from_checkpoint(pl_sd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
        pl_sd = pl_sd.pop("state_dict", pl_sd)
                ^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'pop'

for loading the animatediff model,

and after generation:
*** Error running postprocess_batch_list: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 78, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 90, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'

Then no git/video even frames generated.
 

### Steps to reproduce the problem

1. Load the latest sdxl base model in automatic1111 web ui
2. write any prompt
3. enable animatediff\
4. press generate

### What should have happened?

1. no error in log
2. gif/frame/video generated

### Commit where the problem happens

plugin

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
*** Error running before_process: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 60, in inject
        self._load(model_name)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 41, in _load
        mm_state_dict = sd_models.read_state_dict(model_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\sd_models.py", line 301, in read_state_dict
        sd = get_state_dict_from_checkpoint(pl_sd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
        pl_sd = pl_sd.pop("state_dict", pl_sd)
                ^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'pop'

*** Error running postprocess_batch_list: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 78, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\huang\Projects\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Users\huang\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 90, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
```

**Comment by AugmentedRealityCat** [comment]
> add command line arg --disable-safe-unpickle

The solution proposed by @continue-revolution in the thread below two days ago has resolved this problem for me. You should give it a try. 
https://github.com/continue-revolution/sd-webui-animatediff/issues/313#issuecomment-1809622187

It would be useful to have a safetensor version of that model at some point - I don't think there is one available yet, but that could probably resolve the problem as well, and it would be a safer solution over the long term.

**Comment by kaishanguai2012** [comment]
same problem,webui1.6+animatediff1.2.1.i think that's problem about the checkpoint(SDXL V10 beta.ckpt)
![QQ图片20231120185028](https://github.com/continue-revolution/sd-webui-animatediff/assets/99189169/a2e58912-ec05-4e63-b418-004897e4fb0e)
