### ISSUE TITLE
[Bug]: 在webui中安装完成之后没有启用菜单

### ISSUE THREAD

**Issue by risdh** [continue-revolution/sd-webui-animatediff#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

安装了插件，之后又安装了模型，但是在文生图，图生图中没有animatediff 的选择菜单
在webUI的扩展中也有显示

### Steps to reproduce the problem

开始安装Temporal Kit
发生了报错不能启动
找到了解决方法
解决方法在命令提示行输入
python -m pip uninstall tqdm
python -m pip install tqdm 
解决Temporal Kit报错不能启动问题
之后就发生了在文生图，图生图中没有animatediff 的选择菜单的问题

### What should have happened?

正常启动

### Commit where the problem happens

[API](http://127.0.0.1:7860/docs)  •  [Github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)  •  [Gradio](https://gradio.app/)  •  [启动配置](http://127.0.0.1:7860/?__theme=dark#)  •  [重载 UI](http://127.0.0.1:7860/)
版本: [v1.6.0-2-g4afaaf8a](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.21  •  gradio: 3.41.2  •  checkpoint: [2bcca2a1cc](https://google.com/search?q=2bcca2a1cc260a5d0f29c45d8f5abf1cdb7630e94dde7987001034b4f303fd5b)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
python -m pip uninstall tqdm
python -m pip install tqdm
```

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.11.1, num models: 9
CivitAI Browser+: Aria2 RPC started
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 14, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "G:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 5, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\sd-webui-aki-v4.4\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 5, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-11-23 17:47:31,639 - ControlNet - INFO - ControlNet v1.1.419
ControlNet preprocessor location: G:\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\annotator\downloads
2023-11-23 17:47:31,720 - ControlNet - INFO - ControlNet v1.1.419
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [2bcca2a1cc] from G:\sd-webui-aki-v4.4\models\Stable-diffusion\RealisticGanMix实感_v1.3.safetensors
Creating model from config: G:\sd-webui-aki-v4.4\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.
Model loaded in 2.0s (load weights from disk: 0.6s, create model: 0.5s, apply weights to model: 0.7s).

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 13.8s (prepare environment: 4.1s, import torch: 2.3s, import gradio: 0.8s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.9s, create ui: 0.8s, gradio launch: 2.3s, app_started_callback: 0.2s).
```

**Comment by continue-revolution** [comment]
自行搜索imageio.v3

**Comment by scofi** [comment]
我也遇到这个问题，但已经安装了 imageio , 问题依旧不知道为啥

**Comment by scofi** [comment]
我解决了这个问题，原因是imageio版本太老了，你先删除再安装或者升级
pip uninstall imageio 
再执行
pip install imageio
