### ISSUE TITLE
[Question] Why I can't successfully enable this plugin? (SDv2.1.2/Controlnet v1.1.419)

### ISSUE THREAD

**Issue by NakiriKajiya** [continue-revolution/sd-webui-animatediff#347]
---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\stable-diffusion-webui\modules\processing.py)

---

**Comment by greathiago** [comment]
Why it's closed? How it was solved?
