### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by ClareXUse** [continue-revolution/sd-webui-animatediff#364]
### Expected behavior

the bug report is following
I failed to open the animdiff and cannot see the panel in the page
I just install the animdiff by [Extention =>Available =>search for the animdiff=>install]
pls sb tell me what happened

fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/': Failed to connect to github.com port 443 after 21067 ms: Couldn't connect to server
venv "D:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
current transparent-background 1.2.3

Launching Web UI with arguments: --no-half-vae
No module 'xformers'. Proceeding without it.
Error loading script: animatediff.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 5, in <module>
    from modules.scripts import PostprocessBatchListArgs, PostprocessImageArgs
ImportError: cannot import name 'PostprocessBatchListArgs' from 'modules.scripts' (D:\ai\stable-diffusion-webui\modules\scripts.py)

Error loading script: animatediff_cn.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 19, in <module>
    from scripts.animatediff_ui import AnimateDiffProcess
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
    from scripts.animatediff_i2ibatch import animatediff_i2ibatch
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Error loading script: animatediff_i2ibatch.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Error loading script: animatediff_infotext.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
    from scripts.animatediff_ui import AnimateDiffProcess
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
    from scripts.animatediff_i2ibatch import animatediff_i2ibatch
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Error loading script: animatediff_infv2v.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 10, in <module>
    from modules.script_callbacks import AfterCFGCallbackParams, cfg_after_cfg_callback
ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (D:\ai\stable-diffusion-webui\modules\script_callbacks.py)

Error loading script: animatediff_latent.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 6, in <module>
    from modules.sd_samplers_common import (approximation_indexes,
ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (D:\ai\stable-diffusion-webui\modules\sd_samplers_common.py)

Error loading script: animatediff_lcm.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_lcm.py", line 9, in <module>
    from modules import shared, sd_samplers_cfg_denoiser, sd_samplers_kdiffusion
ImportError: cannot import name 'sd_samplers_cfg_denoiser' from 'modules' (unknown location)

Error loading script: animatediff_output.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 14, in <module>
    from scripts.animatediff_ui import AnimateDiffProcess
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
    from scripts.animatediff_i2ibatch import animatediff_i2ibatch
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Error loading script: animatediff_prompt.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
    from scripts.animatediff_infotext import write_params_txt
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
    from scripts.animatediff_ui import AnimateDiffProcess
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
    from scripts.animatediff_i2ibatch import animatediff_i2ibatch
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Error loading script: animatediff_ui.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
    from scripts.animatediff_i2ibatch import animatediff_i2ibatch
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
    from modules.processing import (StableDiffusionProcessingImg2Img,
ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\stable-diffusion-webui\modules\processing.py)

Loading weights [7eb674963a] from D:\ai\stable-diffusion-webui\models\Stable-diffusion\hassakuHentaiModel_v13.safetensors
Creating model from config: D:\ai\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\ai\stable-diffusion-webui\models\VAE\Anything-V3.0.vae.pt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(2): ng_deepnegative_v1_75t, verybadimagenegative_v1.3
Model loaded in 7.3s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.4s, apply half(): 0.4s, load VAE: 4.8s, move model to device: 0.6s, load textual inversion embeddings: 0.7s).
Error executing callback ui_tabs_callback for D:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 326, in on_ui_tabs
    ui.load_dataset.set_callbacks(o_update_filter_and_gallery,ui.toprow, ui.dataset_gallery, ui.filter_by_tags, ui.filter_by_selection, ui.batch_edit_captions, update_filter_and_gallery)
  File "D:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\block_load_dataset.py", line 88, in set_callbacks
    self.btn_load_datasets.click(
  File "D:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "D:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 195, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "D:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 940, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "D:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 929, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by continue-revolution** [comment]
you are probably using a very old webui. pls update.

I'll close this issue. If problem still exists then let me know.
