### ISSUE TITLE
[Bug]:  FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by zhongyiwei** [continue-revolution/sd-webui-animatediff#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I have removed the full extension and did a install, 
But I kept getting two  FileNotFoundError: [WinError 3] The system cannot find the path specified
The error repeated twice for some reason:
This is the full error:

Error 1:
Loading weights [0724518c6b] from D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\models\Stable-diffusion\07. XL\juggernautXL_v7Rundiffusion.safetensors
2023-12-25 14:11:34,766 - AnimateDiff - INFO - Injecting LCM to UI.
*** Error calling: D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\modules\scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 41, in ui
        return (AnimateDiffUiGroup().render(is_img2img, motion_module.get_model_dir()),)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 146, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\AI Generator\\3. Latest Web UI\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

Error 2:
*** Error calling: D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\modules\scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 41, in ui
        return (AnimateDiffUiGroup().render(is_img2img, motion_module.get_model_dir()),)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 146, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\AI Generator\\3. Latest Web UI\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

### Steps to reproduce the problem

1. Click on install the app
2. App installed
3. Get the model file in
4. Close the Webui
5. Start the webui
6. This error show up

### What should have happened?

Ideally the AnimatedDiff should load, but it did not

### Commit where the problem happens

webui: 1.6.0 and 1.7.0
extension: Latested Extension 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--deepdanbooru --xformers --listen --share --no-half-vae --api
```

### Console logs

```Shell
Loading weights [0724518c6b] from D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\models\Stable-diffusion\07. XL\juggernautXL_v7Rundiffusion.safetensors
2023-12-25 14:21:55,406 - AnimateDiff - INFO - Injecting LCM to UI.
*** Error calling: D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\modules\scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 41, in ui
        return (AnimateDiffUiGroup().render(is_img2img, motion_module.get_model_dir()),)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 146, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\AI Generator\\3. Latest Web UI\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

---
*** Error calling: D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\modules\scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 41, in ui
        return (AnimateDiffUiGroup().render(is_img2img, motion_module.get_model_dir()),)
      File "D:\AI Generator\3. Latest Web UI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 146, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\AI Generator\\3. Latest Web UI\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

---
```

**Comment by zappityzap** [comment]
It looks like your drive letter might have changed (D: vs E:). Check the settings tab for AnimateDiff and look at "Path to save AnimateDiff motion modules"

**Comment by continue-revolution** [comment]
You need to go to `Settings/AnimateDiff` and change the path to your models there. This was an old problem that has been fixed, but people who install this extension early may face this problem because webui cache your settings.

**Comment by kubakubkub** [comment]
> You need to go to `Settings/AnimateDiff` and change the path to your models there. This was an old problem that has been fixed, but people who install this extension early may face this problem because webui cache your settings.

Is there a way to change it in a cache file or sth? Because my UI is not popping up because of this Error. Just when I delete animatediff folder from my extensions.
