### ISSUE TITLE
[Bug]:     FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/Shareddrives/StableDiffusion/AnimateDiff'

### ISSUE THREAD

**Issue by Li1177** [continue-revolution/sd-webui-animatediff#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

    FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/Shareddrives/StableDiffusion/AnimateDiff'

I almost use Animatediff every day, but today I encountered the error shown above. I did a lot of research and it seems that this bug had appeared before and was fixed on August 22, 2023, in A1111 (Create Gradio temp directory if necessary #12717). However, I am sure the problem only occurred today. After this error appeared, Animatediff could not be successfully installed. Although there is a folder for Animatediff in the extension directory, it does not appear in the StableDiffusion Web UI interface. My StableDiffusion Web UI version is: version: 1.7.0 • python: 3.10.12 • torch: 2.1.0+cu121 • xformers: 0.0.22.post7 • gradio: 3.41.2 • checkpoint: a7662a2ad3. Animatediff is also the latest version, and I have been successfully using the V3 model for over a week now。I am running StableDiffusion Web UI on Google Colab.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

None

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers  --opt-sdp-attention --share
```

### Console logs

```Shell
none
```

### Additional information

Even when I don't use Animatediff, every time I generate a single image, I encounter this error message:
*** Error running before_process: /content/SDVN/extensions/Animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/content/SDVN/modules/scripts.py", line 710, in before_process
        script.before_process(p, *script_args)
    TypeError: AnimateDiffScript.before_process() missing 1 required positional argument: 'params'

---
*** Error running postprocess_image: /content/SDVN/extensions/Animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/content/SDVN/modules/scripts.py", line 774, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
    TypeError: AnimateDiffScript.postprocess_image() missing 1 required positional argument: 'params'

---
*** Error running postprocess: /content/SDVN/extensions/Animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/content/SDVN/modules/scripts.py", line 750, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: AnimateDiffScript.postprocess() missing 1 required positional argument: 'params'

---

**Comment by Li1177** [comment]
I have found the reason. The issue was resolved by entering the correct path in the SD webUI settings under Animatediff -- Path to save AnimateDiff motion modules.
