### ISSUE TITLE
[Bug]: SparseCtrl models cannot be recognized by sd-webui-extension

### ISSUE THREAD

**Issue by JatK1Z** [continue-revolution/sd-webui-animatediff#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

**SparseCtrl** models cannot be recognized by sd-webui-extension

### Steps to reproduce the problem

1. T2V mode (T2I tab in webui)
2. activate animatediff & controlnet extension
3. upload an video in animatediff (V2V type)
4. choose 'scribble_pidinet' preprocessor
5. choose 'mm_sd15_v3_sparsectrl_scribble [60d136f2]' (that i put in <webui>/models/ControlNet)
6. run...

### What should have happened?

sparsectrl model (for animateDiff v3) state dict should be recognized by controlnet extension. （think that i can seek help from [u](https://github.com/continue-revolution/sd-webui-animatediff/issues/363#issuecomment-1845671560)）

### Commit where the problem happens

webui: v1.6.0-2-g4afaaf8a
extension: 
* sd-webui-controlnet: v1.1.431
* sd-webui-animatediff: v1.3.1

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--listen --xformers --api --skip-version-check --skip-prepare-environment --no-half-vae
```

### Console logs

```Shell
2024-01-17 18:31:57,206 - AnimateDiff - INFO - AnimateDiff process start.00:02,  2.71s/it]
2024-01-17 18:31:57,226 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet input blocks.
2024-01-17 18:31:57,226 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet output blocks.
2024-01-17 18:31:57,227 - AnimateDiff - INFO - Setting DDIM alpha.
2024-01-17 18:31:57,290 - AnimateDiff - INFO - Injection finished.
2024-01-17 18:31:57,290 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2024-01-17 18:31:57,290 - AnimateDiff - INFO - Hacking ControlNet.
2024-01-17 18:32:00,862 - ControlNet - INFO - Loading model: mm_sd15_v3_sparsectrl_scribble [60d136f2]
2024-01-17 18:32:00,916 - ControlNet - INFO - Loaded state_dict from [<my_pth>/stable-diffusion-webui/models/ControlNet/mm_sd15_v3_sparsectrl_scribble.safetensors]
*** Error running process: <my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "<my_pth>/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1069, in process
        self.controlnet_hack(p)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1054, in controlnet_hack
        self.controlnet_main_entry(p)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 247, in hacked_main_entry
        model_net = cn_script.load_control_model(p, unet, unit.model)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 347, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 376, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "<my_pth>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_model_guess.py", line 253, in build_model_by_guess
        raise '[ControlNet Error] Cannot recognize the ControlModel!'
    TypeError: exceptions must derive from BaseException
---
100%|█████████████████████████████████████████████████████| 19/19 [00:51<00:00,  2.73s/it]
```

**Comment by JatK1Z** [comment]
Sorry, I haven't read [this](https://github.com/continue-revolution/sd-webui-animatediff/pull/381) before. think this may be the [solution](https://github.com/Mikubill/sd-webui-controlnet/pull/2352/commits/6d1f38482ba2689a7e3b136d367c6d7b2740a7e7), may have a try later today. (Great work, many thanks!!! already followed on [bilibili](https://space.bilibili.com/1549185169)

**Comment by continue-revolution** [comment]
You need the specific commit to actually run sparsectrl. There are two comments in two PRs. You may want to checkout the commit right before that two comments. I will assume that you understand what you need to do for now.

The PR is still a work-in-progress because I am doing magic animate. Pls be patient.
