### ISSUE TITLE
[Bug]: Controlnet suddenly stopped working.

### ISSUE THREAD

**Issue by JustCann** [continue-revolution/sd-webui-animatediff#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I had been generating the same video with 2 cn active. Suddenly I got the following in the cmd window 
*** Error running process: C:\Users\alexi\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\alexi\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1113, in process
        self.controlnet_hack(p)
      File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1098, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\alexi\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

I did a clean install of both cn and animatediff, issue still persists. 

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Should have worked as it did previously with no changes 

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --medram
```

### Console logs

```Shell
See above please.
```

**Comment by JustCann** [comment]
Apologies, finally found the comment regarding the CN update, I realized I accidentally updated. Fixed by using git checkout 10bd9b2. It is now working!!
