### ISSUE TITLE
[Bug]: AttributeError: 'str' object has no attribute 'height'

### ISSUE THREAD

**Issue by RexLeeGrey** [continue-revolution/sd-webui-animatediff#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Instead of generating a moving image
AttributeError: 'str' object has no attribute 'height'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Generate moving pictures, no errors reported.

### Commit where the problem happens

webui: 
extension: animatediff

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
2023-07-30 16:10:55,846 - shared.py [line:200] - INFO: Starting job task(n9qtofso90h7tar)
2023-07-30 16:10:55,846 - AnimateDiff - INFO - AnimateDiff process start with video Max frames 16, FPS 8, duration 2.0,  motion module mm_sd_v15.ckpt.
2023-07-30 16:10:55,849 - AnimateDiff - INFO - Hacking GroupNorm32 forward function.
2023-07-30 16:10:55,849 - AnimateDiff - INFO - Injecting motion module mm_sd_v15.ckpt into SD1.5 UNet input blocks.
2023-07-30 16:10:55,849 - AnimateDiff - INFO - Injecting motion module mm_sd_v15.ckpt into SD1.5 UNet output blocks.
2023-07-30 16:10:55,849 - AnimateDiff - INFO - Injection finished.
2023-07-30 16:10:55,851 - dynamic_prompting.py [line:509] - INFO: Prompt matrix will create 16 images in a total of 1 batches.
Miaoshouai boot assistant: Memory Released!
2023-07-30 16:11:25,342 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-07-30 16:11:25,342 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-07-30 16:11:25,343 - AnimateDiff - INFO - Restoring GroupNorm32 forward function.
2023-07-30 16:11:25,343 - AnimateDiff - INFO - Removal finished.
2023-07-30 16:11:25,343 - AnimateDiff - INFO - Merging images into GIF.
2023-07-30 16:11:27,255 - AnimateDiff - INFO - AnimateDiff process end.
*** Error completing request
*** Arguments: ('task(n9qtofso90h7tar)', '<lora:SMDS_2_standard_Lion-000018:0.65>, desert, smds, sculpture, art, no humans, realistic, abstract, solo, hole, tentacles, lamp, metal, metal, reflection,', '((((blurry)))), ((signature)), ((watermark)), ((((blur)))), wall, ((pedestal)), circle,', [], 20, 18, False, False, 1, 1, 7, 8901234568.0, -1.0, 0, 0, 0, False, 512, 768, False, 0.35, 2, '4x-UltraSharp', 20, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x000001FDAAA531F0>, 0, '<span>(No stats yet, run benchmark in VRAM Estimator tab)</span>', False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', True, 0, 16, 8, 'mm_sd_v15.ckpt', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FDABACB610>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FDABAC9D50>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FDABACB1F0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FDABACA140>, False, '', 0.5, True, False, '', 'Lerp', False, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\n身体\nBODY:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nBODY0.5:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,1,1\n脸部（脸型、发型、眼型、瞳色等）\nFACE:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0\nFACE0.5:1,0,0,0,0,0,0,0,0.8,1,1,0.2,0,0,0,0,0\nFACE0.2:1,0,0,0,0,0,0,0,0.2,0.6,0.8,0.2,0,0,0,0,0\n修手专用\nHAND:1,0,1,1,0.2,0,0,0,0,0,0,0,0,0,0,0,0\n服装（搭配tag使用）\nCLOTHING:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0\n动作（搭配tag使用）\nPOSE:1,0,0,0,0,0,0.2,1,1,1,0,0,0,0,0,0,0\n上色风格（搭配tag使用）\nPALETTE:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\n角色（去风格化）\nKEEPCHAR:1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0\n背景（去风格化）\nKEEPBG:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\n减弱过拟合（等同于OUTALL）\nREDUCEFIT:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, None, False, '0', 'D:\\AIGC\\sd-webui-aki-v4.2\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, '🔄', 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', None, None, False, None, None, False, None, None, False, None, None, False, 50, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\n身体\nBODY:1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1\nBODY0.5:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,1,1\n脸部（脸型、发型、眼型、瞳色等）\nFACE:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0\nFACE0.5:1,0,0,0,0,0,0,0,0.8,1,1,0.2,0,0,0,0,0\nFACE0.2:1,0,0,0,0,0,0,0,0.2,0.6,0.8,0.2,0,0,0,0,0\n修手专用\nHAND:1,0,1,1,0.2,0,0,0,0,0,0,0,0,0,0,0,0\n服装（搭配tag使用）\nCLOTHING:1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0\n动作（搭配tag使用）\nPOSE:1,0,0,0,0,0,0.2,1,1,1,0,0,0,0,0,0,0\n上色风格（搭配tag使用）\nPALETTE:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\n角色（去风格化）\nKEEPCHAR:1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0\n背景（去风格化）\nKEEPBG:1,1,1,1,1,1,0.2,1,0.2,0,0,0.8,1,1,1,0,0\n减弱过拟合（等同于OUTALL）\nREDUCEFIT:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False) {}
    Traceback (most recent call last):
      File "D:\AIGC\sd-webui-aki-v4.2\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\AIGC\sd-webui-aki-v4.2\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\AIGC\sd-webui-aki-v4.2\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "D:\AIGC\sd-webui-aki-v4.2\extensions\sd-webui-prompt-history\lib_history\image_process_hijacker.py", line 25, in process_images
        global_state.add_config( uuid.uuid4().hex, res.prompt[:64], shared.opts.sd_model_checkpoint, res.infotexts[0], res.images[0])
      File "D:\AIGC\sd-webui-aki-v4.2\extensions\sd-webui-prompt-history\scripts\prompt_history_script.py", line 76, in add_config
        new_height = int(new_width * img.height / img.width)
    AttributeError: 'str' object has no attribute 'height'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
```

**Comment by continue-revolution** [comment]
pls disable the prompt history extension.
