### ISSUE TITLE
   AttributeError: 'ControlModel' object has no attribute 'reset'

### ISSUE THREAD

**Issue by protector131090** [continue-revolution/sd-webui-animatediff#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

This ERROR only appears when using ANimatediff with controlnet.... after updating

2024-01-24 11:33:23,217 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
*** Error running process: C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\[scripts.py](https://scripts.py/)", line 619, in process
        script.process(p, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)", line 1117, in process
        self.controlnet_hack(p)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\[controlnet.py](https://controlnet.py/)", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

### Steps to reproduce the problem

Using Animatediff with controlnet

### What should have happened?

no erorrs

### Commit where the problem happens

A1111

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
2024-01-24 11:33:23,217 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
*** Error running process: C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1117, in process
        self.controlnet_hack(p)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'
```

### Additional information

CorolNet works fine without Animatediff

**Comment by protector131090** [comment]
[huchenlei](https://github.com/huchenlei) commented [14 hours ago](https://github.com/Mikubill/sd-webui-controlnet/issues/2563#issuecomment-1906639274)

File an issue in https://github.com/continue-revolution/sd-webui-animatediff please. control_model_guess.py is not supposed to be exposed, and we don't guarantee that the signature does not change.

Here the guess control model function returns a tuple instead of a single value now.

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/issues/363#issuecomment-1845671560

For the time being, please revert to this commit. Any update issue will be resolved in v2, which may take several days / weeks depending on my availability.

**Comment by Helio1997hub** [comment]
I have also encountered this problem. May I ask if this problem has been resolved?

**Comment by Danny-707** [comment]
I have the same problem.
Everything worked on one of the earlier versions, but after some update, it stopped working with animateDiff.
Can anyone advise on how to install previous versions of controlNet?

**Comment by Dreason8** [comment]
Same issue here, none of the Controlnet models are working with Animatediff
