### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by zachysaur** [continue-revolution/sd-webui-animatediff#419]
### Expected behavior

*** Error running process: D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\Webui1111\Webui\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

---

**Comment by zopi4k** [comment]
Wait v2.0.0 ... or [find a down-grade old control net version](https://github.com/continue-revolution/sd-webui-animatediff/issues/412) .... Or pass in ["Forge"](https://github.com/continue-revolution/sd-webui-animatediff/tree/forge/master)

**Comment by jaffster595** [comment]
I was experiencing the same issue earlier today. It was resolved by reverting to an older commit. You can follow the steps in this comment https://github.com/continue-revolution/sd-webui-animatediff/issues/412#issuecomment-1913429785

**Comment by continue-revolution** [comment]
fixed in an early pr merge. such problem should no longer exist later
