### ISSUE TITLE
[Bug]: Getting " RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)" Error since Today

### ISSUE THREAD

**Issue by eliasprompt** [continue-revolution/sd-webui-animatediff#436]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Since today I'm getting this error when using AnimateDiff, yesterday worked perfect

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

It should work properly

### Commit where the problem happens

webui: version: [v1.7.0]•  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •
extension: 4c3ec2e5

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
Already up to date.
venv "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --xformers --ckpt-dir D:\Stable_Diffusion_ALL\Models\Stable-difussion
Style database not found: D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\styles.csv
[-] ADetailer initialized. version: 24.1.2, num models: 9
ControlNet preprocessor location: D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-02-24 00:42:26,105 - ControlNet - INFO - ControlNet v1.1.440
2024-02-24 00:42:26,649 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [66e7645b65] from D:\Stable_Diffusion_ALL\Models\Stable-difussion\HelloYoung25b\helloyoung25d_V10f.safetensors
2024-02-24 00:42:27,097 - AnimateDiff - INFO - Injecting LCM to UI.
2024-02-24 00:42:30,593 - AnimateDiff - INFO - Hacking i2i-batch.
2024-02-24 00:42:30,713 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 153.7s (initial startup: 0.4s, prepare environment: 50.8s, launcher: 0.1s, import torch: 32.3s, import gradio: 17.5s, setup paths: 17.9s, import ldm: 0.2s, initialize shared: 1.6s, other imports: 12.6s, setup codeformer: 3.6s, setup gfpgan: 0.3s, list SD models: 2.0s, load scripts: 8.5s, initialize extra networks: 0.3s, create ui: 5.7s, gradio launch: 2.2s).
Loading VAE weights specified in settings: D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 43.4s (load weights from disk: 6.4s, load config: 0.2s, create model: 1.6s, apply weights to model: 27.4s, apply half(): 0.1s, load VAE: 5.1s, load textual inversion embeddings: 0.5s, calculate empty prompt: 1.9s).
2024-02-24 00:44:16,614 - ControlNet - INFO - Preview Resolution = 576
2024-02-24 00:44:46,293 - ControlNet - INFO - Preview Resolution = 576
2024-02-24 00:44:46,541 - ControlNet - INFO - Loaded state_dict from [D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\pidinet\table5_pidinet.pth]
2024-02-24 00:45:04,091 - AnimateDiff - INFO - AnimateDiff process start.
2024-02-24 00:45:04,148 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
2024-02-24 00:45:21,615 - AnimateDiff - INFO - Guessed mm_sd_v15_v2.ckpt architecture: MotionModuleType.AnimateDiffV2
2024-02-24 00:45:24,452 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2024-02-24 00:45:25,616 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2024-02-24 00:45:25,616 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2024-02-24 00:45:25,617 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2024-02-24 00:45:25,618 - AnimateDiff - INFO - Setting DDIM alpha.
2024-02-24 00:45:25,781 - AnimateDiff - INFO - Injection finished.
2024-02-24 00:45:25,782 - AnimateDiff - INFO - Hacking LoRA module to support motion LoRA
2024-02-24 00:45:25,784 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2024-02-24 00:45:25,786 - AnimateDiff - INFO - Hacking ControlNet.
2024-02-24 00:45:26,164 - ControlNet - INFO - Loading model: control_v11p_sd15_openpose [cab727d4]
2024-02-24 00:45:26,735 - ControlNet - INFO - Loaded state_dict from [D:\Stable_Diffusion_ALL\Models\Controlnet\control_v11p_sd15_openpose.pth]
2024-02-24 00:45:26,736 - ControlNet - INFO - controlnet_default_config
2024-02-24 00:45:29,246 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4](ControlModelType.ControlNet) loaded.
2024-02-24 00:45:29,352 - ControlNet - INFO - Loading preprocessor: dw_openpose_full
2024-02-24 00:45:29,352 - ControlNet - INFO - preprocessor resolution = 576
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.44s/it]
2024-02-24 00:45:31,834 - ControlNet - INFO - Loading model: control_v11p_sd15_softedge [a8575a2a]
2024-02-24 00:45:32,341 - ControlNet - INFO - Loaded state_dict from [D:\Stable_Diffusion_ALL\Models\Controlnet\control_v11p_sd15_softedge.pth]
2024-02-24 00:45:32,342 - ControlNet - INFO - controlnet_default_config
2024-02-24 00:45:34,828 - ControlNet - INFO - ControlNet model control_v11p_sd15_softedge [a8575a2a](ControlModelType.ControlNet) loaded.
2024-02-24 00:45:34,924 - ControlNet - INFO - Loading preprocessor: pidinet_safe
2024-02-24 00:45:34,925 - ControlNet - INFO - preprocessor resolution = 576
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.42it/s]
2024-02-24 00:45:35,494 - ControlNet - INFO - ControlNet Hooked - Time = 9.682617902755737
  0%|                                                                                           | 0/20 [00:01<?, ?it/s]
*** Error completing request?it/s]
*** Arguments: ('task(qk2qq7mu2m7hvmn)', '(masterpiece, best quality:1.3), (25 years old jinxlol:1.5), sitting on a rock playing an ukelele, (a magical waterfall with flowing water behind her:1.1), (closed eyes:1.3), (the music notes burst out from the strings of the ukelele to fill the air:1.5), she is surrounded by (flying and swirling magical music notes:1.7), colorfull and vibrant-fluid dynamic movement of (floating music symbols:1.3) of (crotchet note and octave clef:1.5), the composition captures the essence of (motion and vitality:1.3), placing viewers in the heart of a high-energy moment in the style of studio gibly, nadegata style,  <lora:more_details:0.7>  <lora:nadev1:0.3> <lora:JW:0.2> <lora:NebulaDream_v1:0.2> <lora:Unholy:0.2>  <lora:jinxLeagueOfLegends_v10:1>', '((disfigured)), ((bad art)), ((deformed)),((extra limbs)), ((extra barrel)),((b&w)), weird colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), (((tripod))), (((tube))),ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs, extra legs, extra arms,  EXTRA HANDS, cross-eye, body out of frame, bad art, bad anatomy, (((umbrella))), ((BAD HANDS)), ((BAD FINGERS)), ((watermark, username, nickname, signature, text, letters, characters)), ((open eyes)), ((simple background))', [], 20, 'Euler a', 1, 1, 7, 1024, 576, True, 0.15, 1.1, 'Latent', 11, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000012CA3D71030>, 0, False, '', 0.8, 3024528887, False, -1, 0, 0, 0, False, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000012CA3D70CD0>, UiControlNetUnit(enabled=True, module='dw_openpose_full', model='control_v11p_sd15_openpose [cab727d4]', weight=1, image={'image': array([[[153, 174, 201],
***         [153, 174, 201],
***         [153, 174, 201],
***         ...,
***         [128, 148, 175],
***         [128, 148, 175],
***         [128, 148, 175]],
***
***        [[153, 174, 201],
***         [153, 174, 201],
***         [154, 175, 202],
***         ...,
***         [128, 148, 175],
***         [128, 148, 175],
***         [128, 148, 175]],
***
***        [[155, 173, 201],
***         [156, 174, 202],
***         [156, 174, 202],
***         ...,
***         [129, 149, 176],
***         [129, 149, 176],
***         [129, 149, 176]],
***
***        ...,
***
***        [[ 14,  14,  16],
***         [ 13,  13,  15],
***         [ 15,  15,  17],
***         ...,
***         [128, 108, 105],
***         [125, 107, 106],
***         [135, 117, 117]],
***
***        [[ 13,  13,  15],
***         [ 12,  11,  14],
***         [ 14,  14,  16],
***         ...,
***         [129, 109, 107],
***         [133, 115, 112],
***         [142, 124, 122]],
***
***        [[ 14,  14,  16],
***         [ 13,  13,  15],
***         [ 14,  14,  16],
***         ...,
***         [129, 109, 107],
***         [131, 113, 110],
***         [137, 119, 116]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Just Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='ControlNet is more important', inpaint_crop_input_image=True, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=True, module='softedge_pidisafe', model='control_v11p_sd15_softedge [a8575a2a]', weight=1, image={'image': array([[[153, 174, 201],
***         [153, 174, 201],
***         [153, 174, 201],
***         ...,
***         [128, 148, 175],
***         [128, 148, 175],
***         [128, 148, 175]],
***
***        [[153, 174, 201],
***         [153, 174, 201],
***         [154, 175, 202],
***         ...,
***         [128, 148, 175],
***         [128, 148, 175],
***         [128, 148, 175]],
***
***        [[155, 173, 201],
***         [156, 174, 202],
***         [156, 174, 202],
***         ...,
***         [129, 149, 176],
***         [129, 149, 176],
***         [129, 149, 176]],
***
***        ...,
***
***        [[ 14,  14,  16],
***         [ 13,  13,  15],
***         [ 15,  15,  17],
***         ...,
***         [128, 108, 105],
***         [125, 107, 106],
***         [135, 117, 117]],
***
***        [[ 13,  13,  15],
***         [ 12,  11,  14],
***         [ 14,  14,  16],
***         ...,
***         [129, 109, 107],
***         [133, 115, 112],
***         [142, 124, 122]],
***
***        [[ 14,  14,  16],
***         [ 13,  13,  15],
***         [ 14,  14,  16],
***         ...,
***         [129, 109, 107],
***         [131, 113, 110],
***         [137, 119, 116]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Just Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='ControlNet is more important', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 119, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 438, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 269, in mm_cfg_forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 862, in forward_webui
        raise e
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 859, in forward_webui
        return forward(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 581, in forward
        control = param.control_model(
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 31, in forward
        return self.control_model(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 300, in forward
        guided_hint = self.input_hint_block(hint, emb, context)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 102, in forward
        x = layer(x)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 501, in network_Conv2d_forward
        return originals.Conv2d_forward(self, input)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
        return self._conv_forward(input, self.weight, self.bias)
      File "D:\Stable_Diffusion_AUTOMATIC1111_v1.7.0\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
        return F.conv2d(input, weight, bias, self.stride,
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)
```

### Additional information

 **Only happens when CN is enabled** Reinstalled all again in a clean install and updated all extensions but still same problem.

**Comment by guangzou** [comment]
the same as me
