### ISSUE TITLE
[Bug]:  A lot of assert error and  exception, such as  AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

### ISSUE THREAD

**Issue by hellangleZ** [continue-revolution/sd-webui-animatediff#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

couldn't create the vdieo, nother gif or mp4
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/15274284/c9faf9a3-37f9-494e-afa9-636431ac8b3e)

### Steps to reproduce the problem

Latest version webui and animatediff extentions

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/15274284/a1a4f923-a73a-4ef8-ac94-fe5255be0f96)

### What should have happened?

Just generate as normal is OK

### Commit where the problem happens

webui: 1.8
extension:  latest

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
python launch.py --listen --enable-insecure-extension-access
```

### Console logs

```Shell
(/aml/sd) root123@A200:/aml/sd-webui$ HF_ENDPOINT=https://hf-mirror.com python launch.py --listen --enable-insecure-extension-access
Python 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Launching Web UI with arguments: --listen --enable-insecure-extension-access
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
ControlNet preprocessor location: /aml/sd-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-03-07 05:30:04,007 - ControlNet - INFO - ControlNet v1.1.441
2024-03-07 05:30:04,093 - ControlNet - INFO - ControlNet v1.1.441
Loading weights [e1ea3748ba] from /aml/sd-webui/models/Stable-diffusion/mikeymix25D10_mikeymix25D10.ckpt
Creating model from config: /aml/sd-webui/configs/v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 2.9s (load weights from disk: 1.2s, create model: 0.2s, apply weights to model: 1.0s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.1s).
2024-03-07 05:30:07,364 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://0.0.0.0:7860

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB

To create a public link, set `share=True` in `launch()`.
Startup time: 14.6s (prepare environment: 4.7s, import torch: 2.8s, import gradio: 0.9s, setup paths: 0.9s, initialize shared: 0.3s, other imports: 0.3s, load scripts: 1.1s, create ui: 3.2s, gradio launch: 0.3s).
2024-03-07 05:31:05,013 - AnimateDiff - INFO - AnimateDiff process start.
2024-03-07 05:31:05,014 - AnimateDiff - INFO - Loading motion module mm_sd_v14.ckpt from /aml/sd-webui/extensions/sd-webui-animatediff/model/mm_sd_v14.ckpt
2024-03-07 05:31:05,448 - AnimateDiff - INFO - Guessed mm_sd_v14.ckpt architecture: MotionModuleType.AnimateDiffV1
2024-03-07 05:31:08,101 - AnimateDiff - INFO - Hacking SD1.5 GroupNorm32 forward function.
*** Error running before_process: /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/scripts.py", line 776, in before_process
        script.before_process(p, *script_args)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 63, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_mm.py", line 78, in inject
        if self.mm.is_hotshot:
           ^^^^^^^^^^^^^^^^^^
      File "/aml/sd/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'MotionWrapper' object has no attribute 'is_hotshot'

---
  0%|                                                                                                                              | 0/20 [00:00<?, ?it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 90, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
  5%|█████▉                                                                                                                | 1/20 [00:00<00:05,  3.19it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py        | 0/20 [00:00<?, ?it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 15%|█████████████████▋                                                                                                    | 3/20 [00:00<00:02,  8.29it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py| 3/20 [00:00<00:00, 28.20it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 25%|█████████████████████████████▌                                                                                        | 5/20 [00:00<00:01, 11.76it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
                                                                                                                                                         *** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py | 6/20 [00:00<00:00, 22.26it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 35%|█████████████████████████████████████████▎                                                                            | 7/20 [00:00<00:00, 14.13it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 45%|█████████████████████████████████████████████████████                                                                 | 9/20 [00:00<00:00, 15.75it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py| 9/20 [00:00<00:00, 20.91it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 55%|████████████████████████████████████████████████████████████████▎                                                    | 11/20 [00:00<00:00, 16.88it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
                                                                                                                                                         *** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py| 12/20 [00:00<00:00, 20.28it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 65%|████████████████████████████████████████████████████████████████████████████                                         | 13/20 [00:00<00:00, 17.61it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 75%|███████████████████████████████████████████████████████████████████████████████████████▊                             | 15/20 [00:01<00:00, 18.15it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py 15/20 [00:00<00:00, 19.95it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 85%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 17/20 [00:01<00:00, 18.49it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
                                                                                                                                                         *** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py| 18/20 [00:00<00:00, 19.70it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 19/20 [00:01<00:00, 18.70it/s]*** Error executing callback cfg_denoiser_callback for /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
                               ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 15.42it/s]
*** Error running postprocess_batch_list: /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py████████████| 20/20 [00:00<00:00, 19.60it/s]
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/scripts.py", line 832, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 80, in postprocess_batch_list
        params.prompt_scheduler.save_infotext_img(p)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: /aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/aml/sd-webui/modules/scripts.py", line 816, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/aml/sd-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 90, in postprocess
        params.prompt_scheduler.save_infotext_txt(res)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
```

### Additional information

Not only 1.5 but also XL

**Comment by continue-revolution** [comment]
for the time being, use a newer motion module. I will fix this in a day.

**Comment by continue-revolution** [comment]
update and try again. if not working then let me know

**Comment by hellangleZ** [comment]
> update and try again. if not working then let me know

Hi,  It's working at SD1.5, but withe SDXL scenario, it still not working

**Comment by continue-revolution** [comment]
If you are using hotshotxl, you will need to use the model from my hf repo. Otherwise, report the full terminal log here.

**Comment by hellangleZ** [comment]
> If you are using hotshotxl, you will need to use the model from my hf repo. Otherwise, report the full terminal log here.

I just copy you code of motion.py and change the original file , and 1.5 works well, for you suggestion, you mean I need download new model of sdxl, am I right?

**Comment by continue-revolution** [comment]
if you are using adxl beta, you do not need to do anything; if you are using hotshotxl, use https://huggingface.co/conrevo/AnimateDiff-A1111/resolve/main/motion_module/mm_sdxl_hs.safetensors?download=true

**Comment by hellangleZ** [comment]
> if you are using adxl beta, you do not need to do anything; if you are using hotshotxl, use https://huggingface.co/conrevo/AnimateDiff-A1111/resolve/main/motion_module/mm_sdxl_hs.safetensors?download=true

Hey. appreciate for your help, after using the mm_sdxl_hs with the hotshot file, it works good for SDXL

**Comment by xgt1986627** [comment]
I have use both two XL models but still not work. "AttributeError: 'dict' object has no attribute 'shape'"

![MOVIE BUG](https://github.com/continue-revolution/sd-webui-animatediff/assets/50009292/cc67fbdc-3979-4f97-894d-013730300503)

**Comment by continue-revolution** [comment]
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/63914308/9111f289-5b51-498d-8d44-471a7cc77bc0)
@xgt1986627

**Comment by xgt1986627** [comment]
> ![image](https://private-user-images.githubusercontent.com/63914308/311968665-9111f289-5b51-498d-8d44-471a7cc77bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTczMDQsIm5iZiI6MTcxMDI5NzAwNCwicGF0aCI6Ii82MzkxNDMwOC8zMTE5Njg2NjUtOTExMWYyODktNWI1MS00OThkLThkNDQtNDcxYTdjYzc3YmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjA0N2FiOTYwMzBkYWQyMmYwNGMwMmJiMGUyYWFiYWE1YTI1ZWI4OTQzMWY1OWEzNTEwY2ZiMzMzNzFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnJ_bkHRgsg_EmTcIohBBGgiGyCSZCF1r7W6OSoV75g) @xgt1986627

thanks, I have set as you mentioned,but still get"AttributeError: 'dict' object has no attribute 'shape'"

**Comment by xgt1986627** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63914308/311968665-9111f289-5b51-498d-8d44-471a7cc77bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTczMDQsIm5iZiI6MTcxMDI5NzAwNCwicGF0aCI6Ii82MzkxNDMwOC8zMTE5Njg2NjUtOTExMWYyODktNWI1MS00OThkLThkNDQtNDcxYTdjYzc3YmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjA0N2FiOTYwMzBkYWQyMmYwNGMwMmJiMGUyYWFiYWE1YTI1ZWI4OTQzMWY1OWEzNTEwY2ZiMzMzNzFmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnJ_bkHRgsg_EmTcIohBBGgiGyCSZCF1r7W6OSoV75g) @xgt1986627
> 
> thanks, I have set as you mentioned,but still get"AttributeError: 'dict' object has no attribute 'shape'"

this problem only showed in XL model and 1.5 is OK
