### ISSUE TITLE
[Bug]: 更新秋叶包后出现了TypeError: Value after * must be an iterable, not NoneType

### ISSUE THREAD

**Issue by yangl5619** [continue-revolution/sd-webui-animatediff#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

用秋叶整合包1.8版本和webui forge最新版本，使用animatediff都会报错，TypeError: Value after * must be an iterable, not NoneType

### Steps to reproduce the problem

1. 秋叶包自动更新后，或者打开forge
2. 使用animatediff就会报错重启
3. 这几天使用forge也一样，一直都是这个错误

### What should have happened?

应该是正常启用，普通的文生视频都不可以用

### Commit where the problem happens

[Diagnostics-1710251265.log](https://github.com/continue-revolution/sd-webui-animatediff/files/14574028/Diagnostics-1710251265.log)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### Console logs

```Shell
Loading VAE weights specified in settings: F:\sd-webui-aki-v4.6\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 1.3s (create model: 0.2s, apply weights to model: 0.8s).
2024-03-12 21:47:13,309 - ControlNet - [0;32mINFO[0m - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for F:\sd-webui-aki-v4.6\extensions\sd-webui-supermerger\scripts\supermerger.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4.6\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "F:\sd-webui-aki-v4.6\extensions\sd-webui-supermerger\scripts\supermerger.py", line 406, in on_ui_tabs
        mgallery, mgeninfo, mhtmlinfo, mhtmllog = create_output_panel("txt2img", opts.outdir_txt2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for F:\sd-webui-aki-v4.6\extensions\sd-webui-supermerger\scripts\GenParamGetter.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4.6\modules\script_callbacks.py", line 153, in app_started_callback
        c.callback(demo, app)
      File "F:\sd-webui-aki-v4.6\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 90, in get_params_components
        inputs=[*components.msettings,components.esettings1,*components.genparams,*components.hiresfix,*components.lucks,components.currentmodel,components.dfalse,*components.txt2img_params],
    TypeError: Value after * must be an iterable, not NoneType
```

**Comment by continue-revolution** [comment]
I’m not familiar with super merger. Please deactivate it and retry
