### ISSUE TITLE
[Bug]: Can't generate GIF with prompt travel

### ISSUE THREAD

**Issue by TraceIvan** [continue-revolution/sd-webui-animatediff#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I set number of frames as 16 and context batch size as 16. After clicking generate button, I got the IndexError wong:
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/27859479/4691bfb3-848d-4ea0-8668-29e7d1fc2fc3)

### Steps to reproduce the problem

1. Write the positive prompts:
```
(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,
0: wearing winter jacket,boots,(snowing, winter:1.4),
4: wearing autumn cardigan,autumn leaves,fall,(red leaves:1.4),
8: wearing summer dress,sunny,(rose garden:1.4),
12: wearing bikini,beach,sea,(waves:1.4),
```
2. Write the negative prompts:
```
((3d,cartoon, anime,sketches)),(worst quality:2),(low quality:2),lowres,normal quality,((monochrome)),((grayscale)),bad anatomy,out of view,cut off,ugly,deformed,mutated,(bad-hands-5, badhandv4:1.4),ng_deepnegative_v1_75t,(skin spots, blemishes, age spots, acne:1.4),
```
3. Set width=512, height=768
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/27859479/979c9655-db75-4178-a5ca-d2992e4a5491)

4. Enable AnimateDiff, set number of frames as 16 and context batch size as 16
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/27859479/634cf80c-d2ef-4be6-aba1-21bffce3cd4e)

5. Enable Adetailer
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/27859479/9c139192-83ec-443e-9e7e-038e2c7e3262)

6. Click generate button and waiting...

### What should have happened?

It should generate one GIF of 16 frames correctly.

### Commit where the problem happens

webui: 1.8.0
extension: 
[sd-webui-animatediff](https://github.com/continue-revolution/sd-webui-animatediff.git)
[adetailer](https://github.com/Bing-su/adetailer.git)
[sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet.git)
[sd-webui-prompt-all-in-one](https://github.com/Physton/sd-webui-prompt-all-in-one.git)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
python webui.py --theme dark --xformers --api
```

### Console logs

```Shell
*** Error running postprocess_image: E:\stable-diffusion-webui\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\stable-diffusion-webui\modules\scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\stable-diffusion-webui\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    ValueError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮    │                                                        System info                                                                                                               │    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                       │    │ ┃             ┃ Value                                                                                                    ┃                                                       │    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                                       │    │ │    Platform │ Windows-10-10.0.19041-SP0                                                                                │                                                       │    │ │      Python │ 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]         │                                                       │    │ │     Version │ v1.8.0                                                                                                   │                                                       │    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5                                                                 │                                                       │    │ │ Commandline │ ['webui.py', '--theme', 'dark', '--xformers', '--api']                                                   │                                                       │    │ │   Libraries │ {'torch': '2.1.0+cu118', 'torchvision': '0.16.0+cu118', 'ultralytics': '8.0.223', 'mediapipe': '0.10.9'} │                                                       │    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                                       │    │                                                                                      Inputs                                                                                      │    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │    │ ┃                 ┃ Value                                                                                                                                                      ┃ │    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │    │ │          prompt │ ['(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at               │ │    │ │                 │ viewer,smiling,, wearing winter jacket,boots,(snowing, winter:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium      │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing winter jacket,boots,(snowing, winter:1.4),, ',                      │ │    │ │                 │ '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at                │ │    │ │                 │ viewer,smiling,, wearing winter jacket,boots,(snowing, winter:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium      │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing winter jacket,boots,(snowing, winter:1.4),, ',                      │ │    │ │                 │ '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at                │ │    │ │                 │ viewer,smiling,, wearing autumn cardigan,autumn leaves,fall,(red leaves:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful          │ │    │ │                 │ female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing autumn cardigan,autumn leaves,fall,(red leaves:1.4),, │ │    │ │                 │ ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at             │ │    │ │                 │ viewer,smiling,, wearing autumn cardigan,autumn leaves,fall,(red leaves:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful          │ │    │ │                 │ female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing autumn cardigan,autumn leaves,fall,(red leaves:1.4),, │ │    │ │                 │ ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at             │ │    │ │                 │ viewer,smiling,, wearing summer dress,sunny,(rose garden:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium           │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing summer dress,sunny,(rose garden:1.4),, ',                           │ │    │ │                 │ '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at                │ │    │ │                 │ viewer,smiling,, wearing summer dress,sunny,(rose garden:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium           │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing summer dress,sunny,(rose garden:1.4),, ',                           │ │    │ │                 │ '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at                │ │    │ │                 │ viewer,smiling,, wearing bikini,beach,sea,(waves:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium                   │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing bikini,beach,sea,(waves:1.4),, ',                                   │ │    │ │                 │ '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium tits,intricate,hyperdetailed,windy,dramatic,waking,looking at                │ │    │ │                 │ viewer,smiling,, wearing bikini,beach,sea,(waves:1.4),, ', '(realistic),(photorealistic:1.4),raw photo,full body,beautiful female,medium                   │ │    │ │                 │ tits,intricate,hyperdetailed,windy,dramatic,waking,looking at viewer,smiling,, wearing bikini,beach,sea,(waves:1.4),, ']                                   │ │    │ │ negative_prompt │ ((3d,cartoon, anime,sketches)),(worst quality:2),(low quality:2),lowres,normal quality,((monochrome)),((grayscale)),bad anatomy,out of view,cut            │ │    │ │                 │ off,ugly,deformed,mutated,(bad-hands-5, bad
---

0: 640x448 1 face, 32.0ms
Speed: 3.0ms preprocess, 32.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 448)
  0%|                                                                                                                                                            | 0/9 [00:00<?, ?it/s]*** Error executing callback cfg_denoiser_callback for E:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\stable-diffusion-webui\modules\script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "E:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 90, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
      File "E:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 124, in multi_cond
        single_cond = self.single_cond(i, cond.shape[0], cond, closed_loop)
      File "E:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 111, in single_cond
        return AnimateDiffPromptSchedule.slerp(cond[key_prev], cond[key_next], rate)
    IndexError: index 4 is out of bounds for dimension 0 with size 1

---
```

**Comment by continue-revolution** [comment]
for the time being - close adetailer and retry.

I will try to resolve adetailer issue as soon as possible.

**Comment by TraceIvan** [comment]
> for the time being - close adetailer and retry.
> 
> I will try to resolve adetailer issue as soon as possible.

Thank you. After closeing Adetailer, AnimateDiff works. Hopefully compatible with Adetailer.

**Comment by continue-revolution** [comment]
ok. I will try to resolve adetailer issue in #446
