### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'scripts.animatediff_mm'

### ISSUE THREAD

**Issue by Seafood0808** [continue-revolution/sd-webui-animatediff#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Error at startup animatediff becomes invisible in WenUI

### Steps to reproduce the problem

just up data

### What should have happened?

In WenUI, you can see

### Commit where the problem happens

webui: 
extension:9ba5eb5

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half
```

### Console logs

```Shell
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "E:\Stb\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stb\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 9, in <module>
        from motion_module import MotionWrapper, MotionModuleType
      File "E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 333
                from scripts import animatediff_mm
        ^
    TabError: inconsistent use of tabs and spaces in indentation

---
ControlNet preprocessor location: E:\Stb\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-20 19:33:17,689 - ControlNet - INFO - ControlNet v1.1.445
2024-04-20 19:33:17,926 - ControlNet - INFO - ControlNet v1.1.445
[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
Loading weights [6ce0161689] from E:\Stb\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: E:\Stb\stable-diffusion-webui\configs\v1-inference.yaml
*** Error calling: E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "E:\Stb\stable-diffusion-webui\modules\scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 43, in ui
        from scripts.animatediff_mm import mm_animatediff as motion_module
    ModuleNotFoundError: No module named 'scripts.animatediff_mm'

---
*** Error calling: E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "E:\Stb\stable-diffusion-webui\modules\scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "E:\Stb\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 43, in ui
        from scripts.animatediff_mm import mm_animatediff as motion_module
    ModuleNotFoundError: No module named 'scripts.animatediff_mm'
```

### Additional information

Works with comfy animatediff

**Comment by lee393322** [comment]
In my case,
Just cut line 43 and paste into line 22.

**Comment by continue-revolution** [comment]
Probably something shit happened when I merged an earlier PR. Will be fixed as soon as possible.

**Comment by Seafood0808** [comment]
> Probably something shit happened when I merged an earlier PR. Will be fixed as soon as possible.

When I try to delete all animatediff files and reinstall it, it works fine. 
I did it once. I don't know why, but it worked this time.

**Comment by legan80** [comment]
> In my case, From extensions\sd-webui-animatediff\scripts\animatediff.py Just cut line 43 and paste into line 22.

I just edited /scripts/animatediff.py and it works fine.
I moved the code **from scripts.animatediff_mm import mm_animatediff as motion_module** to last row of import section of the same file.

**Comment by C0D3M0N** [comment]
> 제 경우에는 Extensions\sd-webui-animatediff\scripts\animatediff.py에서 43행을 잘라서 22행에 붙여넣으면 됩니다.

thanks

**Comment by Gavin-Evans** [comment]
> In my case, From extensions\sd-webui-animatediff\scripts\animatediff.py Just cut line 43 and paste into line 22.

thanks, it works.

**Comment by D-Ogi** [comment]
I faced the same error so I replaced the lines as per:
```
awk 'NR==43{line=$0;next} NR==22{print line} 1' extensions/sd-webui-animatediff/scripts/animatediff.py > temp && mv temp extensions/sd-webui-animatediff/scripts/animatediff.py
```

But now I get:
```
AnimateDiffScript init
AnimateDiffScript init
*** Error calling: /home/desktop/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py/ui
    Traceback (most recent call last):
      File "/home/desktop/stable-diffusion-webui/modules/scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "/home/desktop/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 44, in ui
        motion_module.set_script_dir(script_dir)
    NameError: name 'motion_module' is not defined

---
AnimateDiffScript init
*** Error calling: /home/desktop/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py/ui
    Traceback (most recent call last):
      File "/home/desktop/stable-diffusion-webui/modules/scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "/home/desktop/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 44, in ui
        motion_module.set_script_dir(script_dir)
    NameError: name 'motion_module' is not defined
```

**Comment by continue-revolution** [comment]
update your webui and animatediff to latest and this should be fixed.
