### ISSUE TITLE
[Bug]: Not able to generate Gifs

### ISSUE THREAD

**Issue by vararth** [continue-revolution/sd-webui-animatediff#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Some kind of error in identifying the downloaded .ckpt files leading to a runtime error

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/66017370/4d368bdf-fc01-44b1-a4aa-3270a5755a49)

### Steps to reproduce the problem

1. Downloaded the models from github and placed them in the right directory 
2. Hit the generate button
3. Error

### What should have happened?

Gif should have been generated, instead only a 4x4 grid of 16 images got generated

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--theme dark

git pull

call webui.bat
```

### Console logs

```Shell
:7860/openpose_editor_index:1     Failed to load resource: the server responded with a status of 404 (Not Found)
?__theme=dark:118 Uncaught SyntaxError: Identifier 'ce' has already been declared (at ?__theme=dark:118:11)
registry.npmmirror.com/@lobehub/assets-favicons/1.1.0/files/assets/site.webmanifest:1 Manifest: property 'start_url' ignored, should be same origin as document.
registry.npmmirror.com/@lobehub/assets-favicons/1.1.0/files/assets/site.webmanifest:1 Manifest: property 'scope' ignored. Start url should be within scope of scope URL.
civitai_helper.js?1692951963.57489:337 gradio_ver:3.23.0
civitai_helper.js?1692951963.57489:438 found active tab: undefined
index.js?1692946351.798327:1 sd-webui-3d-open-pose-editor: onUiLoaded
canvas-editor.js?1692958346.8986773:1 [Canvas Editor] loading...
txt-img-to-3d-mode.js?1692958282.0133727:1 [Txt/Img to 3D Model] loading...
index.js?a83964bb:85 i18next: languageChanged en
index.js?a83964bb:85 i18next: initialized Object
index.js?a83964bb:85 0.1.18  2023-04-15 18:50:24
index.js?a83964bb:102 @mediapipe/pose ModuleSymbol(Symbol.toStringTag): "Module"
index.js?a83964bb:102 MyPose ƒ Pv(h){var w=this;h=h||{},this.h=new Ch({locateFile:h.locateFile,files:function(M){return[{url:"pose_solution_packed_assets_loader.js"},{simd:!1,url:"pose_solution_wasm_bin.js"},{simd:!0,url:"pose_sol…
index.js?a83964bb:3440 create editor
(anonymous) @ index.js?a83964bb:3440
index.js?a83964bb:3419 method GetAppVersion Array(0)
index.js?a83964bb:3419 return Object
index.js?a83964bb:3305 Infinity% loaded
index.js?1692946351.798327:1 Method GetAppVersion MessageEvent
index.js?a83964bb:3419 method Pause Array(0)
index.js?a83964bb:3419 return Object
index.js?a83964bb:3419 method Pause Array(0)
index.js?a83964bb:3419 return Object
index.js?1692946351.798327:1 Method Pause MessageEvent
index.js?a83964bb:3305 Infinity% loaded
index.js?1692946351.798327:1 Method Pause MessageEvent
index.js?a83964bb:3305 _o
index.js?a83964bb:3305 Array(2)
index.js?a83964bb:3419 pushCommand
index.js?1692946351.798327:1 Uncaught (in promise) Object
polotno.bundle.js:20 Polotno warning: <Workspace /> component can not automatically detect its size.
Width or height of parent elements is equal 0.
Please make sure it has non-zero size. You may need to adjust it with your styles. <Workspace /> will automatically fit into parent container.
For simpler debugging here is the log of the parent element:
x @ polotno.bundle.js:20
polotno.bundle.js:20 <div tabindex=​"0" class=​"polotno-workspace-container" style=​"width:​ 100%;​ height:​ 100%;​ position:​ relative;​ outline:​ none;​ flex:​ 1 1 0%;​ background-color:​ rgba(232, 232, 232, 0.9)​;​">​…​</div>​<div class=​"polotno-workspace-inner" style=​"position:​ absolute;​ top:​ 0px;​ left:​ 0px;​ width:​ 100%;​ height:​ 100%;​ overflow:​ auto;​">​…​</div>​</div>​
polotno.bundle.js:20 Polotno warning: <Workspace /> component can not automatically detect its size.
Width or height of parent elements is equal 0.
Please make sure it has non-zero size. You may need to adjust it with your styles. <Workspace /> will automatically fit into parent container.
For simpler debugging here is the log of the parent element:
x @ polotno.bundle.js:20
polotno.bundle.js:20 <div tabindex=​"0" class=​"polotno-workspace-container" style=​"width:​ 100%;​ height:​ 100%;​ position:​ relative;​ outline:​ none;​ flex:​ 1 1 0%;​ background-color:​ rgba(232, 232, 232, 0.9)​;​">​…​</div>​
polotno.bundle.js:349 Polotno Free Version. Development or non-commercial usage only. https://polotno.com/
104Blocks.svelte:217 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:217:11
    at Array.forEach (<anonymous>)
    at Pe (Blocks.svelte:215:9)
    at Blocks.svelte:287:7
DevTools failed to load source map: Could not load content for http://127.0.0.1:7860/file=extensions/sd-canvas-editor/blueprint-popover2.css.map: Unexpected end of JSON input
```

### Additional information

List of Extensions I use regularly:
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/66017370/45713d81-4152-461d-8186-a2c2090240e2)

**Comment by zappityzap** [comment]
That error "Please download models manually." means the model files were not found. Double-check you have them in the correct location. Mine are here:
./extensions/sd-webui-animatediff/model/mm_sd_v14.ckpt
./extensions/sd-webui-animatediff/model/mm_sd_v15.ckpt

**Comment by vararth** [comment]
Yeah but I did download the models in the right location.. the process starts and makes individual images on a grid but there is no gif output, even in the folders.

**Comment by continue-revolution** [comment]
Please add ‘print(model_path)’ after https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff.py#L102 and send me the terminal log. You should add this in a new line and have the same indentation as https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff.py#L10

**Comment by Shin52-hz** [comment]
023-10-15 21:07:50,659 - AnimateDiff - INFO - AnimateDiff process start.
2023-10-15 21:07:50,660 - AnimateDiff - INFO - You are using tested mm mm_sd_v15_v2.ckpt.
2023-10-15 21:07:50,670 - AnimateDiff - INFO - Injecting motion module animatediffMotion_v15V2.ckpt into SD1.5 UNet middle block.
*** Error running before_process: D:\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\NovelAI\aki new\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py", line 49, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "D:\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 94, in inject
        unet.middle_block.insert(-1, self.mm.mid_block.motion_modules[0])
      File "D:\NovelAI\aki new\py310\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'TimestepEmbedSequential' object has no attribute 'insert'
---
2023-10-15 21:07:54,261 - AnimateDiff - INFO - Randomizing init_latent according to [1.0, 0.96875, 0.9375, 0.90625, 0.875, 0.84375, 0.8125, 0.78125, 0.75, 0.71875, 0.6875, 0.65625, 0.625, 0.59375, 0.5625, 0.53125].
*** Error running postprocess: D:\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\NovelAI\aki new\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py", line 72, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'
---

I can not generate GIF too.Can i get some help please.

**Comment by sdpfer** [comment]
> ## 023-10-15 21：07：50,659 - 动画差异 - 信息 - 动画差异进程启动。
> 2023-10-15 21：07：50,660 - 动画差异 - 信息 - 您正在使用经过测试的 mm mm_sd_v15_v2.ckpt。
> 2023-10-15 21：07：50,670 - 动画差异 - 信息 - 将运动模块 animatediffMotion_v15V2.ckpt 注入 SD1.5 UNet 中间块。
> 运行before_process时出错： D：\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py 回溯（最近一次调用）：
> 文件 “D：\NovelAI\aki new\modules\scripts.py”，第 611 行，在 before_process
> script.before_process（p， *script_args） 文件中 “D：\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py
> ”，第 49 行，
> before_process motion_module.inject（p.sd_model， params.model）
> 
> 文件 “D：\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff_mm.py”，第 94 行，在注入中
> unet.middle_block.insert（-1， self.mm.mid_block.motion_modules[0]）
> 文件 “D：\NovelAI\aki new\py310\lib\site-packages\torch\nn\modules\module.py”，第 1207 行，在 **getattr**
> raise AttributeError（“'{}' 对象没有属性 '{}'”.format（
> 属性错误： 'TimestepEmbedSequential' 对象没有属性 '插入'
> ## 2023-10-15 21：07：54,261 - AnimateDiff - 信息 - 根据 [1.0， 0.96875， 0.9375， 0.90625， 0.875， 0.84375， 0.8125， 0.78125， 0.75， 0.71875， 0.6875， 0.65625， 0.625， 0.59375， 0.5625， 0.53125] 随机化init_latent。
> 运行后处理时出错：D：\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py 回溯（最近一次调用）：
> 文件 “D：\NovelAI\aki new\modules\scripts.py”，第 651 行，在 postprocess script.postprocess（p， processing， *script_args）
> 文件 “D：\NovelAI\aki new\extensions\sd-webui-animatediff\scripts\animatediff.py
> ”，第 72 行，在 postprocess
> 
> self.cn_hacker.restore（）
> 中属性错误：“NoneType”对象没有属性“还原”
> 我也无法生成 GIF。我可以得到一些帮助吗？
你解决了吗，我跟你一样的问题

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/issues/180#issuecomment-1751666418
