### ISSUE TITLE
[Bug]:  Unable to install extension

### ISSUE THREAD

**Issue by 2575044704** [continue-revolution/sd-webui-animatediff#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Fail to install extensions

### Steps to reproduce the problem

 1.Install extension
2. extension is not able to open

### What should have happened?

Fail to install extensions

### Commit where the problem happens

webui: 1.6.0
extension: latest

### Command Line Arguments

```Shell
Launching Web UI with arguments: --share --xformers --lowram --no-hashing --disable-nan-check --enable-insecure-extension-access --disable-console-progressbars --enable-console-prompts --no-gradio-queue --no-half-vae --api --lyco-dir /kaggle/working/stable-diffusion-webui/models/lyco --opt-sdp-no-mem-attention --opt-split-attention
```

### Console logs

```Shell
*** Error calling: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py/ui
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 85, in ui
        model = gr.Dropdown(choices=model_list, value=model_list[0], label="Motion module", type="value")
    IndexError: list index out of range

---
*** Error calling: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py/ui
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 85, in ui
        model = gr.Dropdown(choices=model_list, value=model_list[0], label="Motion module", type="value")
    IndexError: list index out of range

---
```

**Comment by 2575044704** [comment]
Extension tab is able to see, but I cannot use, the funtion is empty
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/19410065/49fa7178-bfb4-44d7-b16b-607337f11cc2)
