### ISSUE TITLE
[Bug]: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 8, 8]

### ISSUE THREAD

**Issue by baomuhedao** [continue-revolution/sd-webui-animatediff#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

2023-09-11 16:57:06,645 - AnimateDiff - [0;32mINFO[0m - AnimateDiff process start with video Max frames 16, FPS 8, duration 2.0,  motion module mm_sd_v15_v2.ckpt.
2023-09-11 16:57:06,929 - AnimateDiff - [0;32mINFO[0m - Hacking GroupNorm32 forward function.
2023-09-11 16:57:06,929 - AnimateDiff - [0;32mINFO[0m - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2023-09-11 16:57:06,930 - AnimateDiff - [0;32mINFO[0m - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2023-09-11 16:57:06,930 - AnimateDiff - [0;32mINFO[0m - Injection finished.
2023-09-11 16:57:06,930 - AnimateDiff - [0;32mINFO[0m - Setting DDIM alpha.
Data shape for DDIM sampling is (16, 4, 64, 64), eta 0.0
Running DDIM Sampling with 20 timesteps

DDIM Sampler:   0%|          | 0/20 [00:00<?, ?it/s]
DDIM Sampler:   0%|          | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(tspftjnwhis4r2v)', 'a girl,hair fluttering in the wind', 'bad-hands-5 bad-picture-chill-75v EasyNegative verybadimagenegative_v1.3 By bad artist -neg', [], 20, 19, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x7f99248714f0>, 0, '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', True, 0, 16, 8, 'mm_sd_v15_v2.ckpt', False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f98ec3e5700>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f98ec9ea6a0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f98ec7c1e50>, None, False, '0', '/home/ec2-user/stable-diffusion-webui/models/roop/inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/home/ec2-user/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/home/ec2-user/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 794, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/home/ec2-user/stable-diffusion-webui/modules/processing.py", line 1054, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 222, in sample
        samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 51, in launch_sampling
        return func()
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 222, in <lambda>
        samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddim.py", line 104, in sample
        samples, intermediates = self.ddim_sampling(conditioning, size,
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddim.py", line 164, in ddim_sampling
        outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 58, in p_sample_ddim_hook
        res = self.orig_p_sample_ddim(x_dec, cond, ts, *args, unconditional_conditioning=unconditional_conditioning, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddim.py", line 212, in p_sample_ddim
        model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 802, in forward
        h = module(h, emb, context)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 28, in mm_tes_forward
        x = layer(x, context)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 73, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 130, in forward
        hidden_states = self.norm(hidden_states)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 273, in forward
        return F.group_norm(
      File "/home/ec2-user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2530, in group_norm
        return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 8, 8]

### Steps to reproduce the problem

1. Go to txt2img
2. select  checkpoint of  realisticVisionV51_v51VAE.safetensors [15012c538f]
3. With prompt: a girl,hair fluttering in the wind
4. Sampling method is DDIM
5. motion module is mm_sd_v15_v2.ckpt
6. number of frames :16 with fps 8
7. press generate

### What should have happened?

gif  normally  gererated

### Commit where the problem happens

webui: 
extension: 
AnimatedDiff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

### Additional information

sd version: 1.5.1

**Comment by continue-revolution** [comment]
v2 has a different architecture. please update your extension.

**Comment by Sunnyfxz0123** [comment]
sd-webui version:1.6.0
sd-webui-animatediff version: Newest
But same problem，please help~

**Comment by continue-revolution** [comment]
You either disabled hash calculation or downloaded incomplete model.

**Comment by Sunnyfxz0123** [comment]
start cmd args : --theme dark --xformers --upcast-sampling --api --autolaunch.
using mm_sd_v15_v2.ckpt.
opened hash calculation and complete base model. It was successful the first time, but the same problem occurred after that

**Comment by Sunnyfxz0123** [comment]
i closed ADetailer,it works. But face bad
