### ISSUE TITLE
[Bug]: MP4 Generation Error

### ISSUE THREAD

**Issue by videoprice** [continue-revolution/sd-webui-animatediff#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

2023-09-18 11:28:48,655 - AnimateDiff - INFO - Restoring DDIM alpha.███████████████████| 25/25 [01:02<00:00,  3.15s/it]
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removal finished.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Merging images into GIF.
*** Error running postprocess: W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 65, in _save
        imageio.mimsave(video_path_mp4, video_list, fps=params.fps)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\v2.py", line 495, in mimwrite
        return file.write(ims, is_batch=True, **kwargs)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
        self._fh.write(image, **kwargs)
    TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  2.89s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  3.15s/it] 

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

2023-09-18 11:28:48,655 - AnimateDiff - INFO - Restoring DDIM alpha.███████████████████| 25/25 [01:02<00:00,  3.15s/it]
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removal finished.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Merging images into GIF.
*** Error running postprocess: W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 65, in _save
        imageio.mimsave(video_path_mp4, video_list, fps=params.fps)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\v2.py", line 495, in mimwrite
        return file.write(ims, is_batch=True, **kwargs)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
        self._fh.write(image, **kwargs)
    TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  2.89s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  3.15s/it] 

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Restoring DDIM alpha.███████████████████| 25/25 [01:02<00:00,  3.15s/it]
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removal finished.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Merging images into GIF.
*** Error running postprocess: W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 65, in _save
        imageio.mimsave(video_path_mp4, video_list, fps=params.fps)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\v2.py", line 495, in mimwrite
        return file.write(ims, is_batch=True, **kwargs)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
        self._fh.write(image, **kwargs)
    TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  2.89s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  3.15s/it]
```

### Console logs

```Shell
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Restoring DDIM alpha.███████████████████| 25/25 [01:02<00:00,  3.15s/it]
2023-09-18 11:28:48,655 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Removal finished.
2023-09-18 11:28:48,656 - AnimateDiff - INFO - Merging images into GIF.
*** Error running postprocess: W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 51, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 28, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "W:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 65, in _save
        imageio.mimsave(video_path_mp4, video_list, fps=params.fps)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\v2.py", line 495, in mimwrite
        return file.write(ims, is_batch=True, **kwargs)
      File "W:\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
        self._fh.write(image, **kwargs)
    TypeError: TiffWriter.write() got an unexpected keyword argument 'fps'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  2.89s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [01:12<00:00,  3.15s/it]
```

**Comment by continue-revolution** [comment]
@zappityzap

**Comment by zappityzap** [comment]
@videoprice Can you confirm you have not made any changes to the code?

It's trying to save the video_path_mp4 but ImageIO is using TiffWriter for some reason. There is no reference to TIF files in the code. ImageIO may not have something it needs to write MP4, and is falling back to TIFF.

I don't have a Windows system to test on, but you may need to install ffpmeg, or pip install imageio[ffmpeg].

**Comment by Rizferos** [comment]
Had same problem in Windows system. Confirming that installing ffmpeg with "pip install imageio[ffmpeg]" fixed this, thank you!

**Comment by ooplesoft** [comment]
> Had same problem in Windows system. Confirming that installing ffmpeg with "pip install imageio[ffmpeg]" fixed this, thank you!

I am still getting this error, even after running the command.

**Comment by ooplesoft** [comment]
Fixed. For anyone interested, you need to activate the Venv of the project first. Then run "pip install imageio[ffmpeg]"

https://stackoverflow.com/questions/8921188/issue-with-virtualenv-cannot-activate#:~:text=If%20you're%20using%20Windows,might%20need%20to%20capitalize%20Activate.
