### ISSUE TITLE
[Bug]: Api call error after using the latest version

### ISSUE THREAD

**Issue by christopherwolfsaal** [continue-revolution/sd-webui-animatediff#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

An error occured when using .. seems that the array to object mapping was not working

### Steps to reproduce the problem

Make an api call with the parameters below

### What should have happened?

The api call is getting processed

### Commit where the problem happens

webui: 1.6.0
extension: latest

### Command Line Arguments

```Shell
Payload to /sdapi/v1/txt2img endpoint

POST
{
	'prompt': 'cat',
	'steps': 30,
	'sampler_index': 'Euler a',
	'enable_hr': False,
	'denoising_strength': 0,
	'firstphase_width': 0,
	'firstphase_height': 0,
	'hr_scale': 2,
	'hr_second_pass_steps': 0,
	'hr_resize_x': 0,
	'hr_resize_y': 0,
	'seed': 774759018,
	'subseed': -1,
	'subseed_strength': 0,
	'seed_resize_from_h': -1,
	'seed_resize_from_w': -1,
	'batch_size': 1,
	'n_iter': 1,
	'cfg_scale': 7.5,
	'width': 512,
	'height': 512,
	'restore_faces': None,
	'tiling': False,
	'negative_prompt': 'noise, grit, dull, washed out, blurry, deep-fried, hazy, malformed, warped, deformed, text, watermark',
	'eta': 0,
	's_churn': 0,
	's_tmax': 0,
	's_tmin': 0,
	's_noise': 1,
	'override_settings_restore_afterwards': True,
	'alwayson_scripts': {
		'AnimateDiff': {
			'args': [{
					'enable': True,
					'video_length': 16,
					'format': 'MP4',
					'loop_number': 0,
					'fps': 8,
					'model': 'mm_sd_v15_v2.ckpt',
					'reverse': [],
					'latent_power': 1,
					'latent_scale': 32,
					'last_frame': None,
					'latent_power_last': 1,
					'latent_scale_last': 32
				}
			]
		}
	},
	'override_settings': {
		'sd_model_checkpoint': 'absolutereality_v16'
	}
}
```

### Console logs

```Shell
*** Error running before_process_batch: /stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 43, in before_process_batch
        if params.enable and isinstance(p, StableDiffusionProcessingImg2Img):
    AttributeError: 'dict' object has no attribute 'enable'
```

**Comment by zappityzap** [comment]
It seems like when using the API, the functions before_process, before_process_batch and postprocess get passed a dict containing the AnimateDiff parameters instead of an AnimateDiffProcess object. I'm not sure if this is the correct fix. It resolves the errors but exposes another issue with the API call.
```diff
diff --git a/scripts/animatediff.py b/scripts/animatediff.py
index b3c89d3..84f7958 100644
--- a/scripts/animatediff.py
+++ b/scripts/animatediff.py
@@ -32,6 +32,7 @@ class AnimateDiffScript(scripts.Script):
         return (AnimateDiffUiGroup().render(is_img2img, model_dir),)
 
     def before_process(self, p: StableDiffusionProcessing, params: AnimateDiffProcess):
+        if isinstance(params, dict): params = AnimateDiffProcess(**params)
         if params.enable:
             logger.info("AnimateDiff process start.")
             params.set_p(p)
@@ -40,12 +41,14 @@ class AnimateDiffScript(scripts.Script):
     def before_process_batch(
         self, p: StableDiffusionProcessing, params: AnimateDiffProcess, **kwargs
     ):
+        if isinstance(params, dict): params = AnimateDiffProcess(**params)
         if params.enable and isinstance(p, StableDiffusionProcessingImg2Img):
             AnimateDiffI2VLatent().randomize(p, params)
 
     def postprocess(
         self, p: StableDiffusionProcessing, res: Processed, params: AnimateDiffProcess
     ):
+        if isinstance(params, dict): params = AnimateDiffProcess(**params)
         if params.enable:
             motion_module.restore(p.sd_model)
             AnimateDiffOutput().output(p, res, params)
```

With that fix, an API call gives this:
```
$ curl --request POST -H "Content-Type: application/json" --data @file.json http://zz.local:7860/sdapi/v1/txt2img 
{"error":"AttributeError","detail":"","body":"","errors":"'str' object has no attribute 'info'"}
```
And console shows:
```
     File "/home/zz/stable-diffusion-webui/modules/api/api.py", line 387, in text2imgapi
        b64images = list(map(encode_pil_to_base64, processed.images)) if send_images else []
      File "/home/zz/stable-diffusion-webui/modules/api/api.py", line 110, in encode_pil_to_base64
        for key, value in image.info.items():
    AttributeError: 'str' object has no attribute 'info'
```
I think text2imgapi is expecting a PIL image with a .info attribute, but instead it's getting the path of an output file. This line in output() does it. It seems to allow displaying the GIF in the UI. Without it the UI only shows the image grid and frames, but the API call also completes without error and appears to contain image data.
```
        if len(video_paths) > 0:
            res.images = video_paths
```
That's as far as I got with troubelshooting.

**Comment by continue-revolution** [comment]
@zappityzap feel free to submit a PR mentioning to close this issue and I will merge. They will still have to do the patch at #42 to get rid of the error. That's something that API users to do, and I believe that API users should have some idea of coding.

**Comment by imsamurai** [comment]
hi! same problem, i end up with solution with parameters above + sd api dirty hack)
```diff
diff --git a/modules/api/api.py b/modules/api/api.py
index e6edffe7..bee3675a 100644
--- a/modules/api/api.py
+++ b/modules/api/api.py
@@ -103,30 +103,33 @@ def decode_base64_to_image(encoding):

 def encode_pil_to_base64(image):
     with io.BytesIO() as output_bytes:
+        if isinstance(image, str):
+            with open(image, "rb") as image_file:
+                output_bytes.write(image_file.read())
+        else:
+            if opts.samples_format.lower() == 'png':
+                use_metadata = False
+                metadata = PngImagePlugin.PngInfo()
+                for key, value in image.info.items():
+                    if isinstance(key, str) and isinstance(value, str):
+                        metadata.add_text(key, value)
+                        use_metadata = True
+                image.save(output_bytes, format="PNG", pnginfo=(metadata if use_metadata else None), quality=opts.jpeg_quality)
+
+            elif opts.samples_format.lower() in ("jpg", "jpeg", "webp"):
+                if image.mode == "RGBA":
+                    image = image.convert("RGB")
+                parameters = image.info.get('parameters', None)
+                exif_bytes = piexif.dump({
+                    "Exif": { piexif.ExifIFD.UserComment: piexif.helper.UserComment.dump(parameters or "", encoding="unicode") }
+                })
+                if opts.samples_format.lower() in ("jpg", "jpeg"):
+                    image.save(output_bytes, format="JPEG", exif = exif_bytes, quality=opts.jpeg_quality)
+                else:
+                    image.save(output_bytes, format="WEBP", exif = exif_bytes, quality=opts.jpeg_quality)

-        if opts.samples_format.lower() == 'png':
-            use_metadata = False
-            metadata = PngImagePlugin.PngInfo()
-            for key, value in image.info.items():
-                if isinstance(key, str) and isinstance(value, str):
-                    metadata.add_text(key, value)
-                    use_metadata = True
-            image.save(output_bytes, format="PNG", pnginfo=(metadata if use_metadata else None), quality=opts.jpeg_quality)
-
-        elif opts.samples_format.lower() in ("jpg", "jpeg", "webp"):
-            if image.mode == "RGBA":
-                image = image.convert("RGB")
-            parameters = image.info.get('parameters', None)
-            exif_bytes = piexif.dump({
-                "Exif": { piexif.ExifIFD.UserComment: piexif.helper.UserComment.dump(parameters or "", encoding="unicode") }
-            })
-            if opts.samples_format.lower() in ("jpg", "jpeg"):
-                image.save(output_bytes, format="JPEG", exif = exif_bytes, quality=opts.jpeg_quality)
             else:
-                image.save(output_bytes, format="WEBP", exif = exif_bytes, quality=opts.jpeg_quality)
-
-        else:
-            raise HTTPException(status_code=500, detail="Invalid image format")
+                raise HTTPException(status_code=500, detail="Invalid image format")
```
